[package]
name = "projection-store-pg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
analytics = { path = "../analytics" }
chrono.workspace = true
execution-contracts = { path = "../execution-contracts" }
hex.workspace = true
home.workspace = true
projection-core = { path = "../projection-core" }
query-api = { path = "../query-api" }
source-qualification = { path = "../source-qualification" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shared-consumer-core = { path = "../shared-consumer-core" }
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
