import { ScreenBffDefinition } from "./contracts";

const BLOCKER_RAIL_SCREENS = new Set([
  "EXECUTION_PAPER_WORKBENCH_SCREEN",
  "EXECUTION_PAPER_WORKBENCH_VNM_SCREEN",
  "EXECUTION_SANDBOX_CERTIFICATION_SCREEN",
  "EXECUTION_CANARY_CONTROL_ROOM_SCREEN",
  "EXECUTION_LIVE_FULL_OPERATIONS_SCREEN",
]);

const screen = (definition: ScreenBffDefinition): ScreenBffDefinition => {
  const hasBlockerRail = BLOCKER_RAIL_SCREENS.has(definition.screenId);
  return Object.freeze({
    ...definition,
    // BR-EX-55 is a cross-screen composition dependency. BR-EX-58 applies
    // only to stage workbenches. Publishing both here keeps their ownership
    // explicit without inventing a generic browser query endpoint.
    requestIds: Object.freeze([
      ...new Set([
        ...definition.requestIds,
        "BR-EX-55",
        ...(hasBlockerRail ? ["BR-EX-58"] : []),
      ]),
    ]),
    readCapabilities: Object.freeze([
      ...new Set([
        ...definition.readCapabilities,
        "portal.entity-names",
        ...(hasBlockerRail ? ["portal.blocker-catalog"] : []),
      ]),
    ]),
  });
};

/**
 * N20 browser-facing authority. This allowlist intentionally contains screen
 * contracts, never Manager relations, SQL names, upstream origins or generic
 * query selectors. Later phases may change TYPED_UNAVAILABLE to AVAILABLE
 * without changing a screen's stable operation id or route.
 */
export const SCREEN_BFF_CATALOGUE = Object.freeze([
  screen({ screenId: "PAPER_TRADING_SCREEN", uiRoute: "/deployments/paper", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-41"], authorities: ["TRADING_SYSTEM", "DERIVED"], readCapabilities: ["deployments.positions", "deployments.execution-quality", "sessions.current"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionPaperOverviewV1", method: "GET", pathTemplate: "/api/v1/execution/screens/paper", responseContract: "execution.paper-overview.v1", unavailableReason: "N22_PAPER_READ_NOT_DELIVERED", deliveryPhase: "N22" } }),
  screen({ screenId: "SANDBOX_TRADING_SCREEN", uiRoute: "/deployments/sandbox", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-60"], authorities: ["TRADING_SYSTEM", "PORTAL_CONTROL", "DERIVED"], readCapabilities: ["deployments.positions", "reconciliation.current", "sessions.current"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionSandboxOverviewV1", method: "GET", pathTemplate: "/api/v1/execution/screens/sandbox", responseContract: "execution.sandbox-overview.v1", unavailableReason: "N23_SANDBOX_READ_NOT_DELIVERED", deliveryPhase: "N23" } }),
  screen({ screenId: "LIVE_OPERATIONS_SCREEN", uiRoute: "/deployments/live", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-56"], authorities: ["TRADING_SYSTEM", "PORTAL_CONTROL", "DERIVED"], readCapabilities: ["deployments.positions", "accounts.current", "sessions.current"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionLiveOverviewV1", method: "GET", pathTemplate: "/api/v1/execution/screens/live", responseContract: "execution.live-overview.v1", unavailableReason: "N23_LIVE_READ_NOT_DELIVERED", deliveryPhase: "N23" } }),
  screen({ screenId: "EXECUTION_COMMAND_CENTER_SCREEN", uiRoute: "/execution", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-42", "BR-EX-43", "BR-EX-44", "BR-EX-45"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["ops.alerts", "ops.streams", "ops.redis-retention", "portal.activation"], dataApi: { status: "AVAILABLE", operationId: "executionCommandCenterSnapshot", method: "GET", pathTemplate: "/api/v1/execution/command-center", responseContract: "execution.command-center-snapshot.v1", unavailableReason: null, deliveryPhase: "PRE-IAM-03" } }),
  screen({ screenId: "EXECUTION_OPERATIONS_QUEUE_SCREEN", uiRoute: "/execution/operations", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-46"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["portal.operations-workflow", "ops.findings", "ops.dead-letters"], dataApi: { status: "AVAILABLE", operationId: "executionOperationsQueue", method: "GET", pathTemplate: "/api/v1/execution/operations", responseContract: "execution.operations-queue.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b" } }),
  screen({ screenId: "EXECUTION_INCIDENT_DETAIL_SCREEN", uiRoute: "/execution/operations/incidents/:incidentId", resourceKind: "INCIDENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-45"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["portal.operations-workflow", "ops.trace-order", "ops.findings"], dataApi: { status: "AVAILABLE", operationId: "executionIncidentDetail", method: "GET", pathTemplate: "/api/v1/execution/operations/incidents/{resource_id}", responseContract: "execution.incident-detail.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b-F2" } }),
  screen({ screenId: "EXECUTION_APPROVAL_INBOX_SCREEN", uiRoute: "/governance/approvals", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-47"], authorities: ["PORTAL_CONTROL"], readCapabilities: ["portal.governance"], dataApi: { status: "AVAILABLE", operationId: "executionApprovalInbox", method: "GET", pathTemplate: "/api/v1/execution/governance/approvals", responseContract: "governance.approval-inbox.v1", unavailableReason: null, deliveryPhase: "EX-BE-05a" } }),
  screen({ screenId: "EXECUTION_GATE_R1_REVIEW_SCREEN", uiRoute: "/governance/approvals/:approvalId/r1", resourceKind: "APPROVAL", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-67"], authorities: ["PORTAL_CONTROL", "RESEARCH", "DERIVED"], readCapabilities: ["portal.governance", "deployments.execution-quality"], dataApi: { status: "AVAILABLE", operationId: "executionGateR1Review", method: "GET", pathTemplate: "/api/v1/execution/governance/approvals/{resource_id}/r1", responseContract: "governance.r1-review.v1", unavailableReason: null, deliveryPhase: "EX-BE-05a" } }),
  screen({ screenId: "EXECUTION_GATE_R2_REVIEW_SCREEN", uiRoute: "/governance/approvals/:approvalId/r2", resourceKind: "APPROVAL", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-67"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["portal.governance", "accounts.current", "deployments.positions"], dataApi: { status: "AVAILABLE", operationId: "executionGateR2Review", method: "GET", pathTemplate: "/api/v1/execution/governance/approvals/{resource_id}/r2", responseContract: "governance.r2-review.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b" } }),
  screen({ screenId: "EXECUTION_PAPER_EXIT_REVIEW_SCREEN", uiRoute: "/governance/exit-reviews/:reviewId", resourceKind: "REVIEW", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-63"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["portal.governance", "deployments.execution-quality", "reconciliation.current"], dataApi: { status: "AVAILABLE", operationId: "executionPaperExitReview", method: "GET", pathTemplate: "/api/v1/execution/governance/exit-reviews/{resource_id}", responseContract: "governance.paper-exit-review.v1", unavailableReason: null, deliveryPhase: "PRE-IAM-02" } }),
  screen({ screenId: "EXECUTION_PAPER_WORKBENCH_SCREEN", uiRoute: "/deployments/paper/:deploymentId", resourceKind: "DEPLOYMENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-62"], authorities: ["TRADING_SYSTEM", "RESEARCH", "DERIVED"], readCapabilities: ["deployments.positions", "deployments.execution-quality", "orders.list", "orders.fills", "market.candles"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionPaperWorkbenchV1", method: "GET", pathTemplate: "/api/v1/execution/screens/paper/{resource_id}", responseContract: "execution.paper-workbench.v1", unavailableReason: "N22_PAPER_WORKBENCH_NOT_DELIVERED", deliveryPhase: "N22" } }),
  screen({ screenId: "EXECUTION_PAPER_WORKBENCH_VNM_SCREEN", uiRoute: "/deployments/paper/:deploymentId/vn-market", resourceKind: "DEPLOYMENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-62"], authorities: ["TRADING_SYSTEM", "RESEARCH", "DERIVED"], readCapabilities: ["deployments.positions", "deployments.execution-quality", "orders.list", "orders.fills", "market.candles"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionPaperWorkbenchVnmV1", method: "GET", pathTemplate: "/api/v1/execution/screens/paper/{resource_id}/vn-market", responseContract: "execution.paper-workbench-vnm.v1", unavailableReason: "N22_PAPER_WORKBENCH_VNM_NOT_DELIVERED", deliveryPhase: "N22" } }),
  screen({ screenId: "EXECUTION_SANDBOX_CERTIFICATION_SCREEN", uiRoute: "/deployments/sandbox/:deploymentId", resourceKind: "DEPLOYMENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-60", "BR-EX-61"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "BROKER", "DERIVED"], readCapabilities: ["deployments.positions", "reconciliation.current", "accounts.current", "sessions.current"], dataApi: { status: "AVAILABLE", operationId: "executionSandboxCertification", method: "GET", pathTemplate: "/api/v1/execution/deployments/{resource_id}/certification", responseContract: "execution.sandbox-certification.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b-F2" } }),
  screen({ screenId: "EXECUTION_CANARY_CONTROL_ROOM_SCREEN", uiRoute: "/deployments/live/:deploymentId/canary", resourceKind: "DEPLOYMENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-59"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "BROKER", "DERIVED"], readCapabilities: ["portal.activation", "portal.governance", "deployments.positions", "accounts.current", "ops.alerts"], dataApi: { status: "AVAILABLE", operationId: "executionCanaryControlRoom", method: "GET", pathTemplate: "/api/v1/execution/deployments/{resource_id}/canary", responseContract: "execution.canary-control-room.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b-F3" } }),
  screen({ screenId: "EXECUTION_LIVE_FULL_OPERATIONS_SCREEN", uiRoute: "/deployments/live/:deploymentId", resourceKind: "DEPLOYMENT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-57"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "BROKER", "DERIVED"], readCapabilities: ["deployments.positions", "orders.list", "orders.fills", "accounts.current", "reconciliation.current", "market.ticks"], dataApi: { status: "AVAILABLE", operationId: "executionLiveFullOperations", method: "GET", pathTemplate: "/api/v1/execution/deployments/{resource_id}/live", responseContract: "execution.live-full-operations.v1", unavailableReason: null, deliveryPhase: "EX-BE-05b-F3" } }),
  screen({ screenId: "EXECUTION_FULL_BLOTTER_SCREEN", uiRoute: "/deployments/blotter", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-48"], authorities: ["TRADING_SYSTEM", "DERIVED"], readCapabilities: ["orders.list", "orders.fills", "orders.legs", "orders.trace"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionFullBlotterV1", method: "GET", pathTemplate: "/api/v1/execution/screens/blotter", responseContract: "execution.full-blotter.v1", unavailableReason: "N22_BLOTTER_NOT_DELIVERED", deliveryPhase: "N22" } }),
  screen({ screenId: "EXECUTION_ALPHA_360_SCREEN", uiRoute: "/deployments/alphas/:alphaId", resourceKind: "ALPHA", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-49", "BR-EX-50", "BR-EX-64"], authorities: ["TRADING_SYSTEM", "RESEARCH", "DERIVED"], readCapabilities: ["ops.alpha-activity", "deployments.execution-quality", "deployments.contribution", "market.candles"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionAlpha360V1", method: "GET", pathTemplate: "/api/v1/execution/screens/alphas/{resource_id}", responseContract: "execution.alpha-360.v1", unavailableReason: "N25_ALPHA_360_NOT_DELIVERED", deliveryPhase: "N25" } }),
  screen({ screenId: "EXECUTION_PORTFOLIO_360_SCREEN", uiRoute: "/deployments/portfolios/:portfolioId", resourceKind: "PORTFOLIO", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-51", "BR-EX-65", "BR-EX-66"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "RESEARCH", "DERIVED"], readCapabilities: ["deployments.contribution", "portfolios.correlation-samples", "deployments.positions"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionPortfolio360V1", method: "GET", pathTemplate: "/api/v1/execution/screens/portfolios/{resource_id}", responseContract: "execution.portfolio-360.v1", unavailableReason: "N25_PORTFOLIO_360_NOT_DELIVERED", deliveryPhase: "N25" } }),
  screen({ screenId: "EXECUTION_ACCOUNT_BROKER_360_SCREEN", uiRoute: "/deployments/accounts/:accountId", resourceKind: "ACCOUNT", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-52", "BR-EX-53", "BR-EX-54"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "BROKER", "DERIVED"], readCapabilities: ["bindings.snapshot", "bindings.exposure-verdict", "accounts.current", "reconciliation.current"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionAccountBroker360V1", method: "GET", pathTemplate: "/api/v1/execution/screens/accounts/{resource_id}", responseContract: "execution.account-broker-360.v1", unavailableReason: "N26_ACCOUNT_BROKER_360_NOT_DELIVERED", deliveryPhase: "N26" } }),
  screen({ screenId: "EXECUTION_ADMIN_ACTION_DRAWER_SCREEN", uiRoute: "/administration/actions", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN"], requestIds: ["BR-EX-68"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM"], readCapabilities: ["ops.command-journal", "portal.activation"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionAdminActionDrawerV1", method: "GET", pathTemplate: "/api/v1/execution/screens/admin-actions", responseContract: "execution.admin-action-drawer.v1", unavailableReason: "N27_ADMIN_ACTION_DRAWER_NOT_DELIVERED", deliveryPhase: "N27" } }),
  screen({ screenId: "EXECUTION_NEW_APPROVAL_REQUEST_SCREEN", uiRoute: "/governance/approvals/new", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-69"], authorities: ["PORTAL_CONTROL", "RESEARCH"], readCapabilities: ["portal.governance"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionNewApprovalRequestV1", method: "POST", pathTemplate: "/api/v1/execution/governance/approvals", responseContract: "governance.approval-create.v1", unavailableReason: "N24_APPROVAL_CREATE_NOT_DELIVERED", deliveryPhase: "N24" } }),
  screen({ screenId: "EXECUTION_GATE_LIVE_REVIEW_SCREEN", uiRoute: "/governance/approvals/:approvalId/live", resourceKind: "APPROVAL", resourceRequired: true, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-70"], authorities: ["PORTAL_CONTROL", "TRADING_SYSTEM", "DERIVED"], readCapabilities: ["portal.governance", "deployments.execution-quality", "accounts.current"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionGateLiveReviewV1", method: "GET", pathTemplate: "/api/v1/execution/governance/approvals/{resource_id}/live", responseContract: "governance.live-review.v1", unavailableReason: "N23_LIVE_GATE_NOT_DELIVERED", deliveryPhase: "N23" } }),
  screen({ screenId: "EXECUTION_WAIVERS_REGISTER_SCREEN", uiRoute: "/governance/waivers", resourceKind: "WORKSPACE", resourceRequired: false, requiredRoles: ["ADMIN", "USER"], requestIds: ["BR-EX-71"], authorities: ["PORTAL_CONTROL"], readCapabilities: ["portal.governance"], dataApi: { status: "TYPED_UNAVAILABLE", operationId: "executionWaiversRegisterV1", method: "GET", pathTemplate: "/api/v1/execution/governance/waivers", responseContract: "governance.conditions-register.v1", unavailableReason: "N24_WAIVERS_REGISTER_NOT_DELIVERED", deliveryPhase: "N24" } }),
] satisfies readonly ScreenBffDefinition[]);

export const SCREEN_BFF_BY_ID = new Map(
  SCREEN_BFF_CATALOGUE.map((definition) => [definition.screenId, definition]),
);
