/**
 * The canonical command catalogue, inlined for the fixture port.
 *
 * GENERATED from `packages/contracts/fixtures/execution-command-catalog.valid.json`.
 * The browser bundle cannot read that file; `adminCatalog.test.ts` compares this
 * against it on every run, so a drift fails rather than drifts.
 *
 * Regenerate rather than editing by hand.
 */
export const COMMAND_CATALOGUE_FIXTURE = {
  "schema_version": "execution.command-catalog.v1",
  "catalogue_revision": 2,
  "delivery_profile": "fixture",
  "capability": {
    "state": "DISABLED",
    "reason": "EX_BE_05B_F0_CONTRACT_ONLY"
  },
  "source": {
    "trading_system_commit": "9081397de9e981c43b4e0f67fabe747e7ed964c7",
    "cli_map_sha256": "sha256:20c0a785ed81d1510251cbb306d580560ab9b0dc173029eb8844b5a34241e3a0",
    "openapi_sha256": "sha256:c4f6530981752cb9a9610b704416ee422094abc89c1d63d96ceb7918b38a19f6",
    "generated_from_read_only_extract": true
  },
  "scope": {
    "workspace_id": "fixture-workspace",
    "actor_user_id": "fixture-admin",
    "actor_role": "ADMIN",
    "environment": "PAPER",
    "entity": null,
    "requested_risk_tier": null,
    "capability_state": "DISABLED",
    "freshness_state": "UNAVAILABLE",
    "policy_revision": "execution.command-catalogue.f0.v2"
  },
  "total_entries": 64,
  "returned_entries": 64,
  "entries": [
    {
      "key": "account/policy",
      "command": "account",
      "action": "policy",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "PUT",
      "http_path": "/v1/admin/accounts/{account_id}/policy",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "account/reconcile-open-orders",
      "command": "account",
      "action": "reconcile-open-orders",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R2_SANDBOX",
      "source_risk_tier": "R2_SANDBOX",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/accounts/{account_id}/reconcile-open-orders",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "account/reconcile-positions",
      "command": "account",
      "action": "reconcile-positions",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R2_SANDBOX",
      "source_risk_tier": "R2_SANDBOX",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/accounts/{account_id}/reconcile-positions",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "account/seed-paper",
      "command": "account",
      "action": "seed-paper",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/accounts/paper/seed",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "account/state",
      "command": "account",
      "action": "state",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/accounts/{account_id}/state",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "account/sync",
      "command": "account",
      "action": "sync",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R2_SANDBOX",
      "source_risk_tier": "R2_SANDBOX",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/accounts/{account_id}/sync",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1690"
    },
    {
      "key": "allocation/<root>",
      "command": "allocation",
      "action": "<root>",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "UNCLASSIFIED",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/portfolio-allocations",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1617"
    },
    {
      "key": "alpha/inspect",
      "command": "alpha",
      "action": "inspect",
      "group": "ALPHA_DEPLOYMENT",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1570"
    },
    {
      "key": "alpha/register",
      "command": "alpha",
      "action": "register",
      "group": "ALPHA_DEPLOYMENT",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/alphas/register",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1570"
    },
    {
      "key": "authority/create",
      "command": "authority",
      "action": "create",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_TYPED_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:2333"
    },
    {
      "key": "authority/list",
      "command": "authority",
      "action": "list",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_TYPED_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:2333"
    },
    {
      "key": "bracket-audit/<root>",
      "command": "bracket-audit",
      "action": "<root>",
      "group": "ORDER_CONTROL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/order-brackets/lifecycle-audit",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2218"
    },
    {
      "key": "broker/bindings",
      "command": "broker",
      "action": "bindings",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1655"
    },
    {
      "key": "broker/exposure",
      "command": "broker",
      "action": "exposure",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/broker-bindings/{external_account_ref}/exposure",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1655"
    },
    {
      "key": "broker/reconcile-open-orders",
      "command": "broker",
      "action": "reconcile-open-orders",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R2_SANDBOX",
      "source_risk_tier": "R2_SANDBOX",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/broker-bindings/{external_account_ref}/reconcile-open-orders",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1655"
    },
    {
      "key": "broker/reconcile-positions",
      "command": "broker",
      "action": "reconcile-positions",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R2_SANDBOX",
      "source_risk_tier": "R2_SANDBOX",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/broker-bindings/{external_account_ref}/reconcile-positions",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1655"
    },
    {
      "key": "broker/state",
      "command": "broker",
      "action": "state",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/broker-bindings/{external_account_ref}/state",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1655"
    },
    {
      "key": "capital/history",
      "command": "capital",
      "action": "history",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/portfolio-capital/history",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1636"
    },
    {
      "key": "config/apply",
      "command": "config",
      "action": "apply",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1842"
    },
    {
      "key": "config/plan",
      "command": "config",
      "action": "plan",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1842"
    },
    {
      "key": "copy/policies",
      "command": "copy",
      "action": "policies",
      "group": "ALPHA_DEPLOYMENT",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1823"
    },
    {
      "key": "copy/policy",
      "command": "copy",
      "action": "policy",
      "group": "ALPHA_DEPLOYMENT",
      "risk_tier": "UNCLASSIFIED",
      "source_risk_tier": "UNCLASSIFIED",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1823"
    },
    {
      "key": "deployment/state",
      "command": "deployment",
      "action": "state",
      "group": "ALPHA_DEPLOYMENT",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "PATCH",
      "http_path": "/v1/admin/deployments/{deployment_id}/state",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1612"
    },
    {
      "key": "health/<root>",
      "command": "health",
      "action": "<root>",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/health",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1566"
    },
    {
      "key": "ops/alerts",
      "command": "ops",
      "action": "alerts",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/alpha-activity",
      "command": "ops",
      "action": "alpha-activity",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/command-journal",
      "command": "ops",
      "action": "command-journal",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/dead-letters",
      "command": "ops",
      "action": "dead-letters",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/emergency-close",
      "command": "ops",
      "action": "emergency-close",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R3_LIVE_PROTECTIVE",
      "source_risk_tier": "R3_LIVE_PROTECTIVE",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": true,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/emergency-close-verify",
      "command": "ops",
      "action": "emergency-close-verify",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R3_LIVE_PROTECTIVE",
      "source_risk_tier": "R3_LIVE_PROTECTIVE",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": true,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/ops/emergency-close/{operation_id}/verify",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/findings",
      "command": "ops",
      "action": "findings",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/redis-retention",
      "command": "ops",
      "action": "redis-retention",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/streams",
      "command": "ops",
      "action": "streams",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "ops/trace-order",
      "command": "ops",
      "action": "trace-order",
      "group": "OPERATIONS_INCIDENTS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "UNPUBLISHED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1985"
    },
    {
      "key": "order-group/list",
      "command": "order-group",
      "action": "list",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2169"
    },
    {
      "key": "order-group/show",
      "command": "order-group",
      "action": "show",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2169"
    },
    {
      "key": "performance/account",
      "command": "performance",
      "action": "account",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "performance/account-history",
      "command": "performance",
      "action": "account-history",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/performance/accounts/{account_id}/history",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "performance/dashboard",
      "command": "performance",
      "action": "dashboard",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/performance/dashboard",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "performance/instrument",
      "command": "performance",
      "action": "instrument",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/performance/instruments/latest",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "performance/portfolio",
      "command": "performance",
      "action": "portfolio",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "performance/portfolio-history",
      "command": "performance",
      "action": "portfolio-history",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/performance/portfolios/{portfolio_id}/history",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2034"
    },
    {
      "key": "portfolio/create",
      "command": "portfolio",
      "action": "create",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1592"
    },
    {
      "key": "portfolio/list",
      "command": "portfolio",
      "action": "list",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/portfolios",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1592"
    },
    {
      "key": "portfolio/state",
      "command": "portfolio",
      "action": "state",
      "group": "ACCOUNT_CAPITAL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "PATCH",
      "http_path": "/v1/admin/portfolios/{portfolio_id}/state",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1592"
    },
    {
      "key": "redis/alpha-auth",
      "command": "redis",
      "action": "alpha-auth",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_TYPED_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1936"
    },
    {
      "key": "redis/get",
      "command": "redis",
      "action": "get",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "GENERIC_REDIS_ACCESS_PROHIBITED",
      "source_reference": "cli/__main__.py:1936"
    },
    {
      "key": "redis/scan",
      "command": "redis",
      "action": "scan",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "GENERIC_REDIS_ACCESS_PROHIBITED",
      "source_reference": "cli/__main__.py:1936"
    },
    {
      "key": "redis/stream",
      "command": "redis",
      "action": "stream",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "UNCLASSIFIED",
      "source_risk_tier": "UNCLASSIFIED",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_TYPED_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1936"
    },
    {
      "key": "redis/trading-state",
      "command": "redis",
      "action": "trading-state",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "DIRECT_ACCESS_PROHIBITED",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "TRADING_SYSTEM_TYPED_HTTP_ROUTE_UNPUBLISHED",
      "source_reference": "cli/__main__.py:1936"
    },
    {
      "key": "replay/compare",
      "command": "replay",
      "action": "compare",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/replay/compare",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/create",
      "command": "replay",
      "action": "create",
      "group": "ORDER_CONTROL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/events",
      "command": "replay",
      "action": "events",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/events",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/export",
      "command": "replay",
      "action": "export",
      "group": "ORDER_CONTROL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/replay/export",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/jobs",
      "command": "replay",
      "action": "jobs",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/lifecycle",
      "command": "replay",
      "action": "lifecycle",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/replay/order-lifecycle",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/quantbt-diff",
      "command": "replay",
      "action": "quantbt-diff",
      "group": "ORDER_CONTROL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/replay/quantbt-diff",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/run",
      "command": "replay",
      "action": "run",
      "group": "ORDER_CONTROL",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R1_PAPER_MUTATION",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/replay/jobs/{replay_id}/run",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "replay/show",
      "command": "replay",
      "action": "show",
      "group": "ORDER_CONTROL",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2123"
    },
    {
      "key": "risk/profile",
      "command": "risk",
      "action": "profile",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:1783"
    },
    {
      "key": "risk/state",
      "command": "risk",
      "action": "state",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R1_PAPER_MUTATION",
      "source_risk_tier": "R0_READ",
      "owner_review_required": true,
      "plan_required": true,
      "apply_required": true,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "POST",
      "http_path": "/v1/admin/trading-state",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:1783"
    },
    {
      "key": "sizing/decision",
      "command": "sizing",
      "action": "decision",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2079"
    },
    {
      "key": "sizing/history",
      "command": "sizing",
      "action": "history",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "AMBIGUOUS",
      "http_method": null,
      "http_path": null,
      "blocked_reason": "SOURCE_ROUTE_MAPPING_AMBIGUOUS",
      "source_reference": "cli/__main__.py:2079"
    },
    {
      "key": "sizing/summary",
      "command": "sizing",
      "action": "summary",
      "group": "PLATFORM_DIAGNOSTICS",
      "risk_tier": "R0_READ",
      "source_risk_tier": "R0_READ",
      "owner_review_required": false,
      "plan_required": false,
      "apply_required": false,
      "verify_required": false,
      "portal_reachable": false,
      "source_route_state": "OBSERVED",
      "http_method": "GET",
      "http_path": "/v1/admin/sizing/decisions/summary",
      "blocked_reason": "COMMAND_RELAY_DISABLED",
      "source_reference": "cli/__main__.py:2079"
    }
  ]
} as const;

/**
 * The canonical F0 plan: BLOCKED, no apply token, relay DISABLED.
 *
 * GENERATED from `packages/contracts/fixtures/execution-command-plan.valid.json`;
 * `adminCatalog.test.ts` compares it against that file on every run.
 */
export const COMMAND_PLAN_FIXTURE = {
  "schema_version": "execution.command-plan.v1",
  "operation_id": "op_01K3COMMANDPLAN000000000000",
  "command_type": "EXECUTION_COMMAND",
  "command_version": 1,
  "command_key": "account/sync",
  "risk_tier": "R2_SANDBOX",
  "payload_hash": "sha256:1111111111111111111111111111111111111111111111111111111111111111",
  "plan_digest": "sha256:2222222222222222222222222222222222222222222222222222222222222222",
  "status": "BLOCKED",
  "blockers": [
    "COMMAND_RELAY_DISABLED"
  ],
  "warnings": [],
  "apply_token": null,
  "expires_at": "2026-08-22T12:05:00Z",
  "relay_capability": "DISABLED",
  "source_side_effect_requested": false,
  "payload_storage_policy": "HASH_ONLY_NO_RAW",
  "replayed": false
} as const;
