import { EXECUTION_PREVIEW_SCREEN_IDS } from "./previewRegistry";
import type { ContractAuthorityResponse } from "./screenDataContract";

/**
 * Frontend owns the rendering target and URLs. The server publishes semantic
 * screen/action IDs only; this explicit crosswalk prevents a list screen from
 * being quietly rendered through an unrelated 360 detail panel.
 */
export const BACKEND_SCREEN_TO_FRONTEND_RENDERER = {
  PAPER_TRADING_SCREEN: "EXECUTION_PAPER_WORKBENCH_SCREEN",
  SANDBOX_TRADING_SCREEN: "EXECUTION_SANDBOX_CERTIFICATION_SCREEN",
  LIVE_OPERATIONS_SCREEN: "EXECUTION_LIVE_FULL_OPERATIONS_SCREEN",
  EXECUTION_COMMAND_CENTER_SCREEN: "EXECUTION_COMMAND_CENTER_SCREEN",
  EXECUTION_OPERATIONS_QUEUE_SCREEN: "EXECUTION_OPERATIONS_QUEUE_SCREEN",
  EXECUTION_INCIDENT_DETAIL_SCREEN: "EXECUTION_INCIDENT_DETAIL_SCREEN",
  EXECUTION_APPROVAL_INBOX_SCREEN: "EXECUTION_APPROVAL_INBOX_SCREEN",
  EXECUTION_GATE_R1_REVIEW_SCREEN: "EXECUTION_GATE_R1_REVIEW_SCREEN",
  EXECUTION_GATE_R2_REVIEW_SCREEN: "EXECUTION_GATE_R2_REVIEW_SCREEN",
  EXECUTION_PAPER_EXIT_REVIEW_SCREEN: "EXECUTION_PAPER_EXIT_REVIEW_SCREEN",
  EXECUTION_PAPER_WORKBENCH_SCREEN: "EXECUTION_PAPER_WORKBENCH_SCREEN",
  EXECUTION_PAPER_WORKBENCH_VNM_SCREEN: "EXECUTION_PAPER_WORKBENCH_VNM_SCREEN",
  EXECUTION_SANDBOX_CERTIFICATION_SCREEN: "EXECUTION_SANDBOX_CERTIFICATION_SCREEN",
  EXECUTION_CANARY_CONTROL_ROOM_SCREEN: "EXECUTION_CANARY_CONTROL_ROOM_SCREEN",
  EXECUTION_LIVE_FULL_OPERATIONS_SCREEN: "EXECUTION_LIVE_FULL_OPERATIONS_SCREEN",
  EXECUTION_FULL_BLOTTER_SCREEN: "EXECUTION_FULL_BLOTTER_SCREEN",
  EXECUTION_ALPHA_FLEET_LIST_SCREEN: "EXECUTION_ALPHA_FLEET_LIST_SCREEN",
  EXECUTION_ALPHA_360_SCREEN: "EXECUTION_ALPHA_360_SCREEN",
  EXECUTION_PORTFOLIO_360_SCREEN: "EXECUTION_PORTFOLIO_360_SCREEN",
  EXECUTION_ACCOUNTS_BINDINGS_LIST_SCREEN: "EXECUTION_ACCOUNTS_BINDINGS_LIST_SCREEN",
  EXECUTION_ACCOUNT_BROKER_360_SCREEN: "EXECUTION_ACCOUNT_BROKER_360_SCREEN",
  EXECUTION_ADMIN_ACTION_DRAWER_SCREEN: "EXECUTION_ADMIN_ACTION_DRAWER_SCREEN",
  EXECUTION_NEW_APPROVAL_REQUEST_SCREEN: "EXECUTION_NEW_APPROVAL_REQUEST_SCREEN",
  EXECUTION_GATE_LIVE_REVIEW_SCREEN: "EXECUTION_GATE_LIVE_REVIEW_SCREEN",
  EXECUTION_WAIVERS_REGISTER_SCREEN: "EXECUTION_WAIVERS_REGISTER_SCREEN",
} as const;

export function assertContractAuthorityRouteGraph(contract: ContractAuthorityResponse): boolean {
  const manifests = contract.screen_data_manifest.screens as readonly { screen_id: string; actions: readonly Record<string, unknown>[] }[];
  const actionScreens = new Set(
    (contract.action_manifest.actions as readonly { source_screen_id: string }[]).map((action) => action.source_screen_id),
  );
  for (const screen of manifests) {
    const renderer = BACKEND_SCREEN_TO_FRONTEND_RENDERER[screen.screen_id as keyof typeof BACKEND_SCREEN_TO_FRONTEND_RENDERER];
    if (!renderer || !EXECUTION_PREVIEW_SCREEN_IDS.has(renderer as never)) return false;
    if (screen.actions.some((action) => JSON.stringify(action).toLowerCase().includes("href"))) return false;
    actionScreens.delete(screen.screen_id);
  }
  return actionScreens.size === 0;
}
