[package]
name = "maximum-data-return"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
maximum-data-acceptance = { path = "../maximum-data-acceptance" }
maximum-data-adapter = { path = "../maximum-data-adapter" }
maximum-data-contract = { path = "../maximum-data-contract" }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
