#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="${ROOT_DIR}/repos.conf"
LOCK_FILE="${ROOT_DIR}/repos.lock"
MODE="sync"

usage() {
  cat <<'EOF'
Usage: ./scripts/sync-repos.sh [--locked | --update-lock]

Without an option, fetch each configured child repository, prune stale remote
refs, fetch tags and create/update matching local tracking branches. It does
not switch the currently checked-out branch.

  --locked       After fetching, detach each child worktree at repos.lock.
                 Intended for repeatable CI/image builds; it may reject a
                 child worktree with local changes.
  --update-lock  Resolve every configured default branch after fetching and
                 rewrite repos.lock. Review and commit that file in the parent
                 repository to promote a child revision into the stack.
EOF
}

if [[ ! -f "${MANIFEST}" ]]; then
  printf 'Repository manifest not found: %s\n' "${MANIFEST}" >&2
  exit 1
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --locked)
      [[ "${MODE}" == "sync" ]] || { usage >&2; exit 2; }
      MODE="locked"
      ;;
    --update-lock)
      [[ "${MODE}" == "sync" ]] || { usage >&2; exit 2; }
      MODE="update-lock"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [[ "${MODE}" == "locked" && ! -f "${LOCK_FILE}" ]]; then
  printf 'Lock file not found: %s\n' "${LOCK_FILE}" >&2
  exit 1
fi

ensure_tracking_branches() {
  local repository="$1"
  local branch
  while IFS= read -r branch; do
    [[ "${branch}" == "HEAD" ]] && continue
    if git -C "${repository}" show-ref --verify --quiet "refs/heads/${branch}"; then
      git -C "${repository}" branch --set-upstream-to="origin/${branch}" "${branch}" >/dev/null
    else
      git -C "${repository}" branch --track "${branch}" "origin/${branch}" >/dev/null
    fi
  done < <(git -C "${repository}" for-each-ref --format='%(refname:strip=3)' refs/remotes/origin)
}

locked_revision() {
  local wanted_name="$1"
  local lock_name revision ignored
  while IFS='|' read -r lock_name revision ignored; do
    [[ -z "${lock_name}" || "${lock_name}" == \#* ]] && continue
    [[ -z "${ignored}" ]] || {
      printf 'Invalid lock row for %s\n' "${lock_name}" >&2
      exit 1
    }
    if [[ "${lock_name}" == "${wanted_name}" ]]; then
      printf '%s\n' "${revision}"
      return 0
    fi
  done < "${LOCK_FILE}"
  return 1
}

lock_tmp=""
cleanup() {
  [[ -z "${lock_tmp}" || ! -e "${lock_tmp}" ]] || rm -f -- "${lock_tmp}"
}
trap cleanup EXIT

if [[ "${MODE}" == "update-lock" ]]; then
  lock_tmp="$(mktemp "${ROOT_DIR}/.repos.lock.XXXXXX")"
  printf '%s\n' '# name|commit' > "${lock_tmp}"
  printf '%s\n' '# Generated by ./scripts/portal lock; review before committing.' >> "${lock_tmp}"
fi

while IFS='|' read -r name relative_path remote_url default_branch extra; do
  [[ -z "${name}" || "${name}" == \#* ]] && continue
  [[ -n "${relative_path}" && -n "${remote_url}" && -n "${default_branch}" && -z "${extra}" ]] || {
    printf 'Invalid manifest row for %s\n' "${name}" >&2
    exit 1
  }

  repository="${ROOT_DIR}/${relative_path}"
  if [[ -e "${repository}" && ! -d "${repository}/.git" ]]; then
    printf 'Refusing to use %s: it exists but is not a Git worktree.\n' "${repository}" >&2
    exit 1
  fi

  if [[ ! -e "${repository}" ]]; then
    mkdir -p "$(dirname "${repository}")"
    git clone --origin origin "${remote_url}" "${repository}"
  else
    configured_url="$(git -C "${repository}" remote get-url origin)"
    if [[ "${configured_url}" != "${remote_url}" ]]; then
      printf 'Refusing to rewrite origin for %s. Expected %s, found %s.\n' \
        "${name}" "${remote_url}" "${configured_url}" >&2
      exit 1
    fi
  fi

  git -C "${repository}" fetch origin --prune --tags
  ensure_tracking_branches "${repository}"

  case "${MODE}" in
    locked)
      revision="$(locked_revision "${name}")" || {
        printf 'No locked revision for %s in %s\n' "${name}" "${LOCK_FILE}" >&2
        exit 1
      }
      git -C "${repository}" rev-parse --verify --quiet "${revision}^{commit}" >/dev/null || {
        printf 'Locked revision %s for %s is unavailable after fetch.\n' "${revision}" "${name}" >&2
        exit 1
      }
      git -C "${repository}" checkout --detach "${revision}" >/dev/null
      printf 'Synced %s (%s) at locked revision %s\n' "${name}" "${relative_path}" "${revision}"
      ;;
    update-lock)
      revision="$(git -C "${repository}" rev-parse --verify "origin/${default_branch}^{commit}")"
      printf '%s|%s\n' "${name}" "${revision}" >> "${lock_tmp}"
      printf 'Synced %s (%s); locked default branch %s at %s\n' \
        "${name}" "${relative_path}" "${default_branch}" "${revision}"
      ;;
    sync)
      printf 'Synced %s (%s); default branch: %s\n' "${name}" "${relative_path}" "${default_branch}"
      ;;
  esac
done < "${MANIFEST}"

if [[ "${MODE}" == "update-lock" ]]; then
  mv "${lock_tmp}" "${LOCK_FILE}"
  lock_tmp=""
  printf 'Updated %s\n' "${LOCK_FILE}"
fi
