#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage: ./scripts/verify-workspace.sh

Checks the Portal monorepo source boundaries, protected strategy integrity,
shell syntax and both rendered Docker Compose definitions.
EOF
}

if [[ $# -ne 0 ]]; then
  usage >&2
  exit 2
fi

for required in \
  "${ROOT_DIR}/compose.yaml" \
  "${ROOT_DIR}/deploy/compose.production.yaml" \
  "${ROOT_DIR}/deploy/.env.production.example" \
  "${ROOT_DIR}/deploy/.env.development.example" \
  "${ROOT_DIR}/constraints/portal.txt" \
  "${ROOT_DIR}/vendor/hmd-reader/README.md" \
  "${ROOT_DIR}/.gitignore" \
  "${ROOT_DIR}/.dockerignore" \
  "${ROOT_DIR}/.githooks/lib/access-policy.sh" \
  "${ROOT_DIR}/.githooks/pre-applypatch" \
  "${ROOT_DIR}/.githooks/pre-commit" \
  "${ROOT_DIR}/.githooks/pre-merge-commit" \
  "${ROOT_DIR}/.githooks/pre-push" \
  "${ROOT_DIR}/.githooks/pre-rebase" \
  "${ROOT_DIR}/apps/portal/backend/pyproject.toml" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/api/ingress.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/api/routes_portal.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/adapters/planning_summary.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/adapters/quantbt_summary.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/domain/portal_registry.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/domain/portal_links.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/domain/portal_summary.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/repositories/portal_links.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/repositories/portal_registry.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/portal_links.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/portal_registry.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/portal_overview.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_portal_registry_api.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_planning_summary_adapter.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_quantbt_summary_adapter.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_portal_summary_service.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/domain/canonical.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/durable_runs.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/artifact_store.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/job_broker.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/workers/durable_worker.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/workers/durable_worker_main.py" \
  "${ROOT_DIR}/apps/portal/registry/engine-capabilities.v1.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/engine-capabilities.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/engine_capabilities.py" \
  "${ROOT_DIR}/apps/portal/registry/data-catalog.v1.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/data-catalog.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/data_catalog.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/api/routes_data.py" \
  "${ROOT_DIR}/apps/portal/registry/alphas.v1.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/alpha-manifest.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/alpha_registry.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/api/routes_alphas.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/approval_authority.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/paper_ledger.py" \
  "${ROOT_DIR}/apps/portal/backend/src/portal_api/services/live_control.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_live_control.py" \
  "${ROOT_DIR}/apps/portal/scripts/benchmark_query_path.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_benchmark_gate.py" \
  "${ROOT_DIR}/upgrade/backend/bar14/benchmark-report.json" \
  "${ROOT_DIR}/apps/portal/scripts/export_release_report.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_release_report.py" \
  "${ROOT_DIR}/upgrade/backend/bar16/release-report.json" \
  "${ROOT_DIR}/features/roadmap-task-board/backend/app/infrastructure/cutover.py" \
  "${ROOT_DIR}/features/roadmap-task-board/backend/tests/test_cutover.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_13_LIVE_CONTROL_AND_OPERATIONAL_SAFETY.md" \
  "${ROOT_DIR}/upgrade/backend/BAR_14_RUST_FAST_PATHS_GATE.md" \
  "${ROOT_DIR}/upgrade/backend/BAR_15_PLANNING_POSTGRES_CUTOVER.md" \
  "${ROOT_DIR}/upgrade/backend/BAR_16_RELEASE_DR_HARDENING.md" \
  "${ROOT_DIR}/upgrade/RESEARCH_EXECUTION_DUAL_CELL_AND_INSTITUTIONAL_UIUX_ADJUSTMENT_GUIDE_v0.5_vi.md" \
  "${ROOT_DIR}/upgrade/PAPER_TO_LIVE_EXECUTION_PORTAL_BACKEND_UIUX_ADJUSTMENT_SPEC_v0.6_vi.md" \
  "${ROOT_DIR}/upgrade/DB_ALPHA_PORTFOLIO_ACCOUNT_SCHEMA_GUIDE.md" \
  "${ROOT_DIR}/upgrade/STRATEGY_IMPORT_AND_RUNTIME_CONTRACT.md" \
  "${ROOT_DIR}/CLAUDE.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_approval_paper.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_12_APPROVAL_PROMOTION_PAPER_SANDBOX.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_alpha_registry.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_11_ALPHA_REGISTRY_AND_RESEARCH_PLATFORM.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_data_catalog.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_10_DATA_CATALOG_AND_IMMUTABLE_SNAPSHOTS.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_engine_capabilities.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_09_ENGINE_CAPABILITY_AUTHORITY.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_durable_worker.py" \
  "${ROOT_DIR}/upgrade/backend/BAR_08_DURABLE_QUANT_WORKER_AND_IMMUTABLE_ARTIFACTS.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-004-OBJECT_STORE_PROVIDER.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-006-WORKER_ISOLATION_AND_SUPERVISION.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_canonical_contracts.py" \
  "${ROOT_DIR}/packages/contracts/README.md" \
  "${ROOT_DIR}/packages/contracts/package.json" \
  "${ROOT_DIR}/packages/contracts/package-lock.json" \
  "${ROOT_DIR}/packages/contracts/contracts-snapshot.json" \
  "${ROOT_DIR}/packages/contracts/tooling/snapshot.py" \
  "${ROOT_DIR}/packages/contracts/schemas/common.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/problem.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/command-envelope.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/event-envelope.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/keyset-page.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-projection-page.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-governance-r2-review.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-governance-approval-workflow.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-governance-paper-exit.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-realtime-event.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-analytics-series.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-event-envelope.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-operations.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-staged-activation.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/problem.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/command.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/event.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/keyset-page.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.capital-preview.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.order-funnel.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-batch.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.correlation.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.capital-ledger.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.binding-exposure.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-projection-page.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.r2-review.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.r1-review.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.approval-history.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.paper-exit-review.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-realtime.auth-expiring.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-realtime.projection-gap.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.equity-projection.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-line.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-histogram.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-funnel.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-waterfall.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-heatmap.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-bar.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-events.corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-catalog.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-plan.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-operation.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-relay-denied.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-operations-queue.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-operation-workflow.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-incident-detail.open.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-incident-workflow.resolved.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-staged-activation.capabilities.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-staged-activation.plan-blocked.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-staged-activation.states.valid.json" \
  "${ROOT_DIR}/packages/contracts/generated/portal-api.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-analytics.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-analytics-series.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-governance.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-realtime.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-operations.d.ts" \
  "${ROOT_DIR}/packages/contracts/generated/execution-staged-activation.d.ts" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-analytics.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-analytics-series.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-governance.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-realtime.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-operations.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-staged-activation.openapi.json" \
  "${ROOT_DIR}/packages/contracts/tooling/generate-execution-command-catalog.mjs" \
  "${ROOT_DIR}/packages/contracts/vitest.config.ts" \
  "${ROOT_DIR}/packages/contracts/test/fixtures.spec.ts" \
  "${ROOT_DIR}/scripts/contracts-test.sh" \
  "${ROOT_DIR}/upgrade/backend/BAR_06_SHARED_CONTRACT_AUTHORITY.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-001-JAVASCRIPT_WORKSPACE_AND_LOCK_AUTHORITY.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-002-OPAQUE_ID_FORMAT.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-005-EVENT_SCHEMA_ENCODING_AND_REGISTRY.md" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_m0_freeze.py" \
  "${ROOT_DIR}/apps/portal/scripts/export_m0_freeze.py" \
  "${ROOT_DIR}/apps/portal/scripts/export_environment_report.py" \
  "${ROOT_DIR}/scripts/verify-m0-golden.sh" \
  "${ROOT_DIR}/upgrade/backend/BAR_05_REPRODUCIBILITY_FREEZE.md" \
  "${ROOT_DIR}/upgrade/backend/bar05/m0-freeze-manifest.json" \
  "${ROOT_DIR}/upgrade/backend/bar05/environment-report.json" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_frontend_handoff.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_compat_parity.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_artifact_provenance.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_portal_links_api.py" \
  "${ROOT_DIR}/apps/portal/backend/tests/test_ingress_boundary.py" \
  "${ROOT_DIR}/apps/portal/frontend/package-lock.json" \
  "${ROOT_DIR}/apps/portal/registry/registry.json" \
  "${ROOT_DIR}/apps/portal/registry/links.v1.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/links.public.json" \
  "${ROOT_DIR}/apps/portal/registry/FRONTEND_HANDOFF.md" \
  "${ROOT_DIR}/apps/portal/registry/openapi/portal-api.openapi.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/registry.public.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.healthy.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.empty.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.partial.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.stale.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.denied.json" \
  "${ROOT_DIR}/apps/portal/registry/fixtures/summary.unavailable.json" \
  "${ROOT_DIR}/apps/portal/scripts/export_handoff_contract.py" \
  "${ROOT_DIR}/apps/portal/scripts/export_compat_snapshots.py" \
  "${ROOT_DIR}/apps/portal/scripts/export_m0_freeze.py" \
  "${ROOT_DIR}/apps/portal/scripts/export_environment_report.py" \
  "${ROOT_DIR}/scripts/verify-m0-golden.sh" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-registry-source.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-registry.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-summary.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-links.v1.schema.json" \
  "${ROOT_DIR}/upgrade/backend/BAR_02_COMPATIBILITY_BOUNDARIES_AND_PARITY_FREEZE.md" \
  "${ROOT_DIR}/upgrade/backend/BAR_03_OPERATIONAL_INGRESS_BOUNDARY.md" \
  "${ROOT_DIR}/deploy/cloudflared/config.example.yml" \
  "${ROOT_DIR}/deploy/nginx/portal-loopback.conf" \
  "${ROOT_DIR}/deploy/edge/README.md" \
  "${ROOT_DIR}/docs/release-and-deployment.md" \
  "${ROOT_DIR}/.github/workflows/ci.yml" \
  "${ROOT_DIR}/.github/workflows/deploy.yml" \
  "${ROOT_DIR}/scripts/verify-migration-history.sh" \
  "${ROOT_DIR}/scripts/verify-release-channel.sh" \
  "${ROOT_DIR}/deploy/nginx/portal.conf" \
  "${ROOT_DIR}/apps/control-api/package.json" \
  "${ROOT_DIR}/apps/control-api/package-lock.json" \
  "${ROOT_DIR}/apps/control-api/tsconfig.json" \
  "${ROOT_DIR}/apps/control-api/vitest.config.ts" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000000_init-identity.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000001_control-facade.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000002_execution-governance.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000003_execution-approval-analytics-scope.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000004_governance-paper-exit.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000005_command-center-pins.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000006_execution-operations-f0.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000007_execution-operations-f0-hardening.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000008_execution-operations-queue.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000009_execution-incidents.sql" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000012_execution-n09-governance-workflow.sql" \
  "${ROOT_DIR}/apps/control-api/src/id.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/workspaces.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/runs.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/outbox.ts" \
  "${ROOT_DIR}/apps/control-api/src/facade/proxy.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/facade/facade.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/facade/session.guard.ts" \
  "${ROOT_DIR}/apps/control-api/src/query/contracts.ts" \
  "${ROOT_DIR}/apps/control-api/src/query/cursor.ts" \
  "${ROOT_DIR}/apps/control-api/src/query/index.ts" \
  "${ROOT_DIR}/apps/control-api/src/query/postgres.ts" \
  "${ROOT_DIR}/apps/control-api/src/query/request.ts" \
  "${ROOT_DIR}/apps/control-api/test/query.spec.ts" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_04A_CONTROL_PLANE_QUERY_PRIMITIVES.md" \
  "${ROOT_DIR}/apps/control-api/src/governance/apply-token.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/contracts.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/governance.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/governance.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/governance.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/paper-exit.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/governance/paper-exit.service.ts" \
  "${ROOT_DIR}/apps/control-api/test/governance-token.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/governance.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/paper-exit.spec.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/contracts.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/catalog.generated.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/operations.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/operations.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/workflow.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/workflow.service.ts" \
  "${ROOT_DIR}/apps/control-api/test/execution-operations.spec.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/incident.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/incident.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/operations/incident.service.ts" \
  "${ROOT_DIR}/apps/control-api/test/incident-workflow.spec.ts" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05B_F1B_INCIDENT_DETAIL.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F1B_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05B_F0_OFFLINE_OPERATIONS_FOUNDATION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F0_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05B_F1A_OPERATIONS_QUEUE.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F1A_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05A_GOVERNANCE_EVIDENCE_APPROVAL.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/Cargo.lock" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/rust-toolchain.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contract-pack.lock.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/execution-contracts/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/execution-contracts/src/events.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/analytics/src/series.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/analytics/src/tiles.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/ts-contract-v1/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/ts-adapter-v1/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/edge-auth/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/ts-transport/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/command-relay/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/command-relay/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/edge-service/src/main.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/edge-service/src/d4_command.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-core/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-core/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/query-api/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/query-api/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/src/d4_writer.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/src/query.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/src/analytics_repository.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/src/shared_consumer.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/shared-consumer-core/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/shared-consumer-core/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/shared-consumer-core/src/tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/shared-consumer-core/fixtures/redacted-snapshots.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-shadow-mapper/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-shadow-mapper/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-shadow-mapper/src/tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/fixtures/d4-paper-shadow-corpus.manifest.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0001_projection_foundation.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0002_projection_query_foundation.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0003_analytics_source_projection.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0004_analytics_integrity_hardening.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0005_projection_event_entity.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0006_projection_operation_and_sequence_semantics.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0007_d4_source_checkpoint.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0008_shared_consumer_lease.sql" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-contract/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-contract/build.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-contract/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-contract/src/tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-ingestor/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-ingestor/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-ingestor/src/tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-runner/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-runner/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-runner/src/tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-transport/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-transport/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/paper-source-transport/src/tests.rs" \
  "${ROOT_DIR}/deploy/images/execution-edge-ci.Dockerfile" \
  "${ROOT_DIR}/deploy/images/execution-edge.Dockerfile" \
  "${ROOT_DIR}/deploy/images/source-proxy.Dockerfile" \
  "${ROOT_DIR}/deploy/compose.execution-edge.yaml" \
  "${ROOT_DIR}/deploy/compose.execution-shadow-query.yaml" \
  "${ROOT_DIR}/deploy/.env.execution-edge.example" \
  "${ROOT_DIR}/scripts/execution-edge-test.sh" \
  "${ROOT_DIR}/scripts/execution-offline-hardening-test.sh" \
  "${ROOT_DIR}/scripts/execution-edge-live-probe.sh" \
  "${ROOT_DIR}/scripts/execution-d1-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d1-open-window.sh" \
  "${ROOT_DIR}/scripts/execution-d1-render-wireguard.sh" \
  "${ROOT_DIR}/scripts/execution-d1-test.sh" \
  "${ROOT_DIR}/scripts/execution-iam-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_iam_verify.py" \
  "${ROOT_DIR}/scripts/execution-d2-host-admission.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_host_admission.py" \
  "${ROOT_DIR}/scripts/execution-d2-authorization.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_authorization.py" \
  "${ROOT_DIR}/scripts/execution-d2-isolation.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_isolation.py" \
  "${ROOT_DIR}/scripts/execution-d2-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d2-render-source-proxy.sh" \
  "${ROOT_DIR}/scripts/execution-d2-test.sh" \
  "${ROOT_DIR}/scripts/execution-d3-render-probe-env.sh" \
  "${ROOT_DIR}/scripts/execution-d3-live-probe.sh" \
  "${ROOT_DIR}/scripts/execution-d3-test.sh" \
  "${ROOT_DIR}/scripts/execution-d4-authorization.py" \
  "${ROOT_DIR}/scripts/test_execution_d4_authorization.py" \
  "${ROOT_DIR}/scripts/execution-d4-dormant-closeout.py" \
  "${ROOT_DIR}/scripts/test_execution_d4_dormant_closeout.py" \
  "${ROOT_DIR}/scripts/execution-n02-contract-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n02_contract_verify.py" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/README.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/owner-pack.manifest.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.schema.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/compatibility-fixtures.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/error-corpus.example.json" \
  "${ROOT_DIR}/scripts/execution-n03-implementation-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n03_implementation_verify.py" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/README.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/owner-implementation.manifest.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/implementation-profile.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/source-metrics.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/query-plan-evidence.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/acceptance-results.example.json" \
  "${ROOT_DIR}/scripts/execution-image-publication-test.sh" \
  "${ROOT_DIR}/scripts/execution-tracking-test.sh" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05_N09_PORTAL_GOVERNANCE_WORKFLOW_GAPS.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N09_GOVERNANCE_WORKFLOW_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_07_N10_SERIES_AND_INSIGHT_ANALYTICS_CONTRACTS.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N10_SERIES_INSIGHT_HANDOFF.md" \
  "${ROOT_DIR}/scripts/execution-n11-external-read-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n11_external_read_verify.py" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/external-read-adapter/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/external-read-adapter/src/lib.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/README.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/capability-catalogue.schema.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/capability-catalogue.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/semantic-rulings.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/golden-corpus-index.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/acceptance-results.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/owner-publication.manifest.example.json" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_01_N11_EXTERNAL_READ_CAPABILITIES_AND_ADAPTERS.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N11_EXTERNAL_READ_HANDOFF.md" \
  "${ROOT_DIR}/scripts/execution-n12-command-publication-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n12_command_publication_verify.py" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/README.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/command-capability-catalogue.schema.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/command-capability-catalogue.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/terminal-corpus-index.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/acceptance-results.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/owner-publication.manifest.example.json" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_05B_N12_LIVE_COMMAND_RELAY.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N12_COMMAND_RELAY_HANDOFF.md" \
  "${ROOT_DIR}/apps/control-api/migrations/1723680000013_execution-staged-activation.sql" \
  "${ROOT_DIR}/apps/control-api/src/activation/contracts.ts" \
  "${ROOT_DIR}/apps/control-api/src/activation/activation.repository.ts" \
  "${ROOT_DIR}/apps/control-api/src/activation/activation.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/activation/activation.controller.ts" \
  "${ROOT_DIR}/apps/control-api/test/staged-activation.spec.ts" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_08_N13A_SOURCE_DARK_STAGED_ACTIVATION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N13A_STAGED_ACTIVATION_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_17_N14A_PORTAL_RELEASE_AUTHORITY_SOURCE_DARK.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N14A_RELEASE_AUTHORITY_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_18_N15A_SOURCE_DARK_FOUR_INTERFACE_GATEWAY.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N15A_FOUR_INTERFACE_GATEWAY_HANDOFF.md" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-intercell-gateway.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.event-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.artifact-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-intercell-gateway.openapi.json" \
  "${ROOT_DIR}/packages/contracts/generated/execution-intercell-gateway.d.ts" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/intercell-gateway/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/intercell-gateway/src/lib.rs" \
  "${ROOT_DIR}/scripts/execution-n15a-gateway-test.sh" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_19_N16A_SOURCE_DARK_ROUTING_AND_EMERGENCY_POLICY.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N16A_EMERGENCY_ROUTING_HANDOFF.md" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-emergency-routing.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-emergency-routing.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-emergency-routing.ui-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-emergency-routing.openapi.json" \
  "${ROOT_DIR}/packages/contracts/generated/execution-emergency-routing.d.ts" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/emergency-routing/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/emergency-routing/src/lib.rs" \
  "${ROOT_DIR}/deploy/execution-emergency/README.md" \
  "${ROOT_DIR}/deploy/execution-emergency/origin-isolation.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-emergency/nginx.same-origin.source-dark.conf.template" \
  "${ROOT_DIR}/scripts/execution-n16a-emergency-routing-test.sh" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_20_N17A_SOURCE_DARK_PRODUCTION_DR_PREPARATION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N17A_PRODUCTION_READINESS_HANDOFF.md" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-production-readiness.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-production-readiness.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-production-readiness.game-day-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-production-readiness.openapi.json" \
  "${ROOT_DIR}/packages/contracts/generated/execution-production-readiness.d.ts" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/production-readiness/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/production-readiness/src/lib.rs" \
  "${ROOT_DIR}/deploy/execution-readiness/README.md" \
  "${ROOT_DIR}/deploy/execution-readiness/slo-alerts.source-dark.yml" \
  "${ROOT_DIR}/deploy/execution-readiness/grafana-dashboard.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/capacity-retention-cost.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/rotation-inventory.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/owner-matrix.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/game-day-plan.source-dark.json" \
  "${ROOT_DIR}/deploy/runbooks/portal-n17a-source-dark-production-dr.md" \
  "${ROOT_DIR}/scripts/execution-n17a-readiness.py" \
  "${ROOT_DIR}/scripts/test_execution_n17a_readiness.py" \
  "${ROOT_DIR}/scripts/execution-n17a-production-dr-test.sh" \
  "${ROOT_DIR}/scripts/build-trading-system-owner-campaign-pack.sh" \
  "${ROOT_DIR}/deploy/manifests/deployment-profile.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/deployment-profiles.source-dark.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-compatibility-matrix.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/compatibility-matrix.source-dark.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-manifest.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-candidate-evidence.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-owner-decision.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/release-manifest.template.json" \
  "${ROOT_DIR}/deploy/manifests/release-candidate-evidence.template.json" \
  "${ROOT_DIR}/deploy/manifests/release-owner-decision.template.json" \
  "${ROOT_DIR}/deploy/runbooks/portal-n14a-source-dark-release-and-rollback.md" \
  "${ROOT_DIR}/scripts/portal-release-authority.py" \
  "${ROOT_DIR}/scripts/test_portal_release_authority.py" \
  "${ROOT_DIR}/scripts/portal-release-authority-test.sh" \
  "${ROOT_DIR}/.github/workflows/publish-images.yml" \
  "${ROOT_DIR}/deploy/execution-d1/README.md" \
  "${ROOT_DIR}/deploy/execution-d1/owner-input.env.example" \
  "${ROOT_DIR}/deploy/execution-d1/edge-source-proxy.env.example" \
  "${ROOT_DIR}/deploy/execution-d1/compose.dark.yaml" \
  "${ROOT_DIR}/deploy/execution-d1/wireguard/portal0.sgp.conf.template" \
  "${ROOT_DIR}/deploy/execution-d1/wireguard/portal0.aws.conf.template" \
  "${ROOT_DIR}/deploy/execution-d1/pki/openssl-workload-profiles.cnf.template" \
  "${ROOT_DIR}/deploy/execution-d1/pki/identity-inventory.md" \
  "${ROOT_DIR}/deploy/execution-d1/source-proxy/nginx.conf.template" \
  "${ROOT_DIR}/deploy/execution-d1/source-proxy/trading-system-read-header.conf.example" \
  "${ROOT_DIR}/deploy/runbooks/execution-d1-bootstrap-and-rollback.md" \
  "${ROOT_DIR}/deploy/execution-d2/README.md" \
  "${ROOT_DIR}/deploy/execution-d2/owner-input.env.example" \
  "${ROOT_DIR}/deploy/execution-d2/init-projection-database.sh" \
  "${ROOT_DIR}/deploy/runbooks/execution-d2-dark-deploy-and-rollback.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D2_AUTHORIZATION_CONTRACT.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_D2_PLACEMENT_DECISION.md" \
  "${ROOT_DIR}/deploy/execution-d3/README.md" \
  "${ROOT_DIR}/deploy/execution-d3/compose.probes.yaml" \
  "${ROOT_DIR}/deploy/runbooks/execution-d3-contract-auth-probes-and-rollback.md" \
  "${ROOT_DIR}/deploy/execution-d4/README.md" \
  "${ROOT_DIR}/deploy/execution-d4/owner-input.env.example" \
  "${ROOT_DIR}/deploy/execution-d4/qualification-runtime.env.example" \
  "${ROOT_DIR}/deploy/execution-d4/storage-input.env.example" \
  "${ROOT_DIR}/deploy/execution-d4/dormant-closeout.env.example" \
  "${ROOT_DIR}/deploy/execution-d4/source-idle-evidence.json.example" \
  "${ROOT_DIR}/deploy/execution-d4/systemd/portal-execution-d4-window-guard.service.example" \
  "${ROOT_DIR}/deploy/execution-d4/compose.encrypted-storage.yaml" \
  "${ROOT_DIR}/deploy/execution-d4/compose.paper-read-shadow.yaml" \
  "${ROOT_DIR}/deploy/execution-d4/source-proxy/nginx.conf.template" \
  "${ROOT_DIR}/deploy/execution-d4/source-proxy/trading-system-read-header.conf.example" \
  "${ROOT_DIR}/deploy/runbooks/execution-d4-paper-shadow-and-rollback.md" \
  "${ROOT_DIR}/scripts/execution-d4-storage-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-render-source-proxy.sh" \
  "${ROOT_DIR}/scripts/execution-d4-source-proxy-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-qualification-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-qualification-preflight-test.sh" \
  "${ROOT_DIR}/scripts/execution-d4-source-proxy-test.sh" \
  "${ROOT_DIR}/scripts/test-execution-d4-storage.sh" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_SOURCE_PROXY_OFFLINE.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_QUALIFICATION_RUNTIME_ENTRYPOINT.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_OFFLINE_AUTHORIZATION_PREPARATION.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_READINESS_AUDIT_AND_OWNER_REQUEST.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_MAPPER_CORE_HARDENING.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_ENCRYPTED_STORAGE_BOUNDARY.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D4_OWNER_ACTION_PACKET.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_D4_DORMANT_CLOSEOUT_DISCIPLINE.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_N02_INCREMENTAL_SOURCE_CONTRACT_REVISION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N02_INCREMENTAL_SOURCE_CONTRACT_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_N03_TRADING_SYSTEM_INCREMENTAL_SOURCE_IMPLEMENTATION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N03_OWNER_IMPLEMENTATION_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_03_N04_LEASE_AWARE_RUST_SHARED_CONSUMER.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N04_LEASE_AWARE_CONSUMER_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_03_N05_RETENTION_RECOVERY_CLEANUP.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_03_N06_REAL_SOURCE_QUALIFICATION_AND_SOAK.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N06_REAL_SOURCE_QUALIFICATION_HANDOFF.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_03_N07_PROJECTION_QUERY_ANALYTICS_SHADOW.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N07_SHADOW_SCREEN_APIS_HANDOFF.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/source-qualification/src/real_source.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/source-qualification/src/real_source_tests.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/source-qualification/src/bin/n06_verify.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/source-qualification/fixtures/n06-real-source-qualification.template.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/source-qualification/src/shadow_screen.rs" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0010_shadow_screen_activation.sql" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-paper-workbench.orders-shadow.valid.json" \
  "${ROOT_DIR}/scripts/execution-n06-qualification-verify.sh" \
  "${ROOT_DIR}/scripts/execution-n06-qualification-test.sh" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D1_OFFLINE_PREPARATION.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D1_EXECUTION_EVIDENCE.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_IAM_VERIFICATION_AND_D1_REVALIDATION.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D2_ADMISSION_CHECKPOINT.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_02_LIVE_D3_OFFLINE_PREPARATION.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_01_RUST_CONTRACTS_AND_TS_ADAPTER.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_03_PROJECTION_REDUCER_REPLAY_FRESHNESS.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_04B_RUST_PROJECTION_QUERY_PRIMITIVES.md" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_07B_SOURCE_BACKED_PROJECTION_REPOSITORIES_AND_SCREEN_APIS.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-007-PORTAL-PROJECTION-EPOCH-CURSOR-AND-FRESHNESS.md" \
  "${ROOT_DIR}/apps/control-api/src/execution/delegation.ts" \
  "${ROOT_DIR}/apps/control-api/src/cli/execution-d3-assertions.ts" \
  "${ROOT_DIR}/apps/control-api/test/execution-delegation.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/execution-d3-assertions.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/facade.spec.ts" \
  "${ROOT_DIR}/upgrade/backend/BAR_07_CONTROL_API_FACADE.md" \
  "${ROOT_DIR}/apps/control-api/src/main.ts" \
  "${ROOT_DIR}/apps/control-api/src/app.ts" \
  "${ROOT_DIR}/apps/control-api/src/app.module.ts" \
  "${ROOT_DIR}/apps/control-api/src/config.ts" \
  "${ROOT_DIR}/apps/control-api/test/config.spec.ts" \
  "${ROOT_DIR}/apps/control-api/src/domain.ts" \
  "${ROOT_DIR}/apps/control-api/src/tokens.ts" \
  "${ROOT_DIR}/apps/control-api/src/http-error.filter.ts" \
  "${ROOT_DIR}/apps/control-api/src/execution/analytics.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/execution/analytics.proxy.ts" \
  "${ROOT_DIR}/apps/control-api/test/execution-analytics.spec.ts" \
  "${ROOT_DIR}/apps/control-api/src/execution/current-source.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/execution/current-source.proxy.ts" \
  "${ROOT_DIR}/apps/control-api/test/execution-current-source.spec.ts" \
  "${ROOT_DIR}/deploy/compose.execution-current-source.yaml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/current-source-v1/README.md" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/current-source-v1/capability-source-map.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/current-source-compat/Cargo.toml" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/crates/current-source-compat/src/lib.rs" \
  "${ROOT_DIR}/upgrade/backend/EX_BE_08_N13B_CURRENT_SOURCE_STAGED_ACTIVATION.md" \
  "${ROOT_DIR}/upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N13B_CURRENT_SOURCE_HANDOFF.md" \
  "${ROOT_DIR}/apps/control-api/src/auth/auth.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/auth.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/argon.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/policy.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/cloudflare.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/principal.ts" \
  "${ROOT_DIR}/apps/control-api/src/auth/cookies.ts" \
  "${ROOT_DIR}/apps/control-api/src/admin/admin.service.ts" \
  "${ROOT_DIR}/apps/control-api/src/admin/admin.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/admin/rbac.guard.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/users.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/bindings.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/credentials.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/sessions.ts" \
  "${ROOT_DIR}/apps/control-api/src/repos/audit.ts" \
  "${ROOT_DIR}/apps/control-api/src/db/pool.ts" \
  "${ROOT_DIR}/apps/control-api/src/health/health.controller.ts" \
  "${ROOT_DIR}/apps/control-api/src/cli/bootstrap.ts" \
  "${ROOT_DIR}/apps/control-api/test/health.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/harness.ts" \
  "${ROOT_DIR}/apps/control-api/test/repos.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/auth.spec.ts" \
  "${ROOT_DIR}/apps/control-api/test/matrix.spec.ts" \
  "${ROOT_DIR}/deploy/images/control-api.Dockerfile" \
  "${ROOT_DIR}/scripts/control-api-test.sh" \
  "${ROOT_DIR}/scripts/control-api-provision-keyrings.sh" \
  "${ROOT_DIR}/upgrade/backend/BAR_04_THIN_IDENTITY_BFF.md" \
  "${ROOT_DIR}/upgrade/backend/adr/ADR-003-POSTGRES_MIGRATION_AND_QUERY_APPROACH.md" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/portal-api.openapi.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/planning-api.openapi.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/run-request.schema.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/manifest.json" \
  "${ROOT_DIR}/apps/portal/strategy/PROTECTED_SHA256" \
  "${ROOT_DIR}/apps/portal/strategy/main.py" \
  "${ROOT_DIR}/features/roadmap-task-board/backend/requirements-dev.txt" \
  "${ROOT_DIR}/features/roadmap-task-board/backend/tests/test_summary_contract.py" \
  "${ROOT_DIR}/features/roadmap-task-board/frontend/package-lock.json"; do
  [[ -f "${required}" ]] || {
    printf 'Required Portal source file is missing: %s\n' "${required}" >&2
    exit 1
  }
done

command -v docker >/dev/null 2>&1 || {
  printf 'Docker CLI is required to validate compose.yaml.\n' >&2
  exit 1
}

if nested_git="$(find "${ROOT_DIR}/apps" "${ROOT_DIR}/features" -name .git -print -quit)"; [[ -n "${nested_git}" ]]; then
  printf 'Nested Git metadata is not allowed in the Portal monorepo: %s\n' "${nested_git}" >&2
  exit 1
fi

for tracked_source in \
  constraints/portal.txt \
  apps/portal/backend/pyproject.toml \
  apps/portal/backend/src/portal_api/api/routes_portal.py \
  apps/portal/backend/src/portal_api/adapters/planning_summary.py \
  apps/portal/backend/src/portal_api/adapters/quantbt_summary.py \
  apps/portal/backend/src/portal_api/domain/portal_registry.py \
  apps/portal/backend/src/portal_api/domain/portal_links.py \
  apps/portal/backend/src/portal_api/domain/portal_summary.py \
  apps/portal/backend/src/portal_api/repositories/portal_links.py \
  apps/portal/backend/src/portal_api/repositories/portal_registry.py \
  apps/portal/backend/src/portal_api/services/portal_links.py \
  apps/portal/backend/src/portal_api/services/portal_registry.py \
  apps/portal/backend/src/portal_api/services/portal_overview.py \
  apps/portal/backend/tests/test_portal_registry_api.py \
  apps/portal/backend/tests/test_planning_summary_adapter.py \
  apps/portal/backend/tests/test_quantbt_summary_adapter.py \
  apps/portal/backend/tests/test_portal_summary_service.py \
  apps/portal/backend/src/portal_api/domain/canonical.py \
  apps/portal/backend/src/portal_api/services/durable_runs.py \
  apps/portal/backend/src/portal_api/services/artifact_store.py \
  apps/portal/backend/src/portal_api/services/job_broker.py \
  apps/portal/backend/src/portal_api/workers/durable_worker.py \
  apps/portal/backend/src/portal_api/workers/durable_worker_main.py \
  apps/portal/registry/engine-capabilities.v1.json \
  apps/portal/registry/schemas/engine-capabilities.v1.schema.json \
  apps/portal/backend/src/portal_api/services/engine_capabilities.py \
  apps/portal/registry/data-catalog.v1.json \
  apps/portal/registry/schemas/data-catalog.v1.schema.json \
  apps/portal/backend/src/portal_api/services/data_catalog.py \
  apps/portal/backend/src/portal_api/api/routes_data.py \
  apps/portal/registry/alphas.v1.json \
  apps/portal/registry/schemas/alpha-manifest.v1.schema.json \
  apps/portal/backend/src/portal_api/services/alpha_registry.py \
  apps/portal/backend/src/portal_api/api/routes_alphas.py \
  apps/portal/backend/src/portal_api/services/approval_authority.py \
  apps/portal/backend/src/portal_api/services/paper_ledger.py \
  apps/portal/backend/src/portal_api/services/live_control.py \
  apps/portal/backend/tests/test_live_control.py \
  apps/portal/scripts/benchmark_query_path.py \
  apps/portal/backend/tests/test_benchmark_gate.py \
  upgrade/backend/bar14/benchmark-report.json \
  apps/portal/scripts/export_release_report.py \
  apps/portal/backend/tests/test_release_report.py \
  upgrade/backend/bar16/release-report.json \
  features/roadmap-task-board/backend/app/infrastructure/cutover.py \
  features/roadmap-task-board/backend/tests/test_cutover.py \
  upgrade/backend/BAR_13_LIVE_CONTROL_AND_OPERATIONAL_SAFETY.md \
  upgrade/backend/BAR_14_RUST_FAST_PATHS_GATE.md \
  upgrade/backend/BAR_15_PLANNING_POSTGRES_CUTOVER.md \
  upgrade/backend/BAR_16_RELEASE_DR_HARDENING.md \
  upgrade/RESEARCH_EXECUTION_DUAL_CELL_AND_INSTITUTIONAL_UIUX_ADJUSTMENT_GUIDE_v0.5_vi.md \
  upgrade/PAPER_TO_LIVE_EXECUTION_PORTAL_BACKEND_UIUX_ADJUSTMENT_SPEC_v0.6_vi.md \
  upgrade/DB_ALPHA_PORTFOLIO_ACCOUNT_SCHEMA_GUIDE.md \
  upgrade/STRATEGY_IMPORT_AND_RUNTIME_CONTRACT.md \
  CLAUDE.md \
  apps/portal/backend/tests/test_approval_paper.py \
  upgrade/backend/BAR_12_APPROVAL_PROMOTION_PAPER_SANDBOX.md \
  apps/portal/backend/tests/test_alpha_registry.py \
  upgrade/backend/BAR_11_ALPHA_REGISTRY_AND_RESEARCH_PLATFORM.md \
  apps/portal/backend/tests/test_data_catalog.py \
  upgrade/backend/BAR_10_DATA_CATALOG_AND_IMMUTABLE_SNAPSHOTS.md \
  apps/portal/backend/tests/test_engine_capabilities.py \
  upgrade/backend/BAR_09_ENGINE_CAPABILITY_AUTHORITY.md \
  apps/portal/backend/tests/test_durable_worker.py \
  upgrade/backend/BAR_08_DURABLE_QUANT_WORKER_AND_IMMUTABLE_ARTIFACTS.md \
  upgrade/backend/adr/ADR-004-OBJECT_STORE_PROVIDER.md \
  upgrade/backend/adr/ADR-006-WORKER_ISOLATION_AND_SUPERVISION.md \
  apps/portal/backend/tests/test_canonical_contracts.py \
  packages/contracts/README.md \
  packages/contracts/package.json \
  packages/contracts/package-lock.json \
  packages/contracts/contracts-snapshot.json \
  packages/contracts/tooling/snapshot.py \
  packages/contracts/schemas/common.v1.schema.json \
  packages/contracts/schemas/problem.v1.schema.json \
  packages/contracts/schemas/command-envelope.v1.schema.json \
  packages/contracts/schemas/event-envelope.v1.schema.json \
  packages/contracts/schemas/keyset-page.v1.schema.json \
  packages/contracts/schemas/execution-projection-page.v1.schema.json \
  packages/contracts/schemas/execution-governance-r2-review.v1.schema.json \
  packages/contracts/schemas/execution-governance-paper-exit.v1.schema.json \
  packages/contracts/schemas/execution-realtime-event.v1.schema.json \
  packages/contracts/schemas/execution-analytics-series.v1.schema.json \
  packages/contracts/schemas/execution-event-envelope.v1.schema.json \
  packages/contracts/schemas/execution-operations.v1.schema.json \
  packages/contracts/schemas/execution-staged-activation.v1.schema.json \
  packages/contracts/fixtures/problem.valid.json \
  packages/contracts/fixtures/command.valid.json \
  packages/contracts/fixtures/event.valid.json \
  packages/contracts/fixtures/keyset-page.valid.json \
  packages/contracts/fixtures/execution-analytics.capital-preview.valid.json \
  packages/contracts/fixtures/execution-analytics.order-funnel.valid.json \
  packages/contracts/fixtures/execution-staged-activation.capabilities.valid.json \
  packages/contracts/fixtures/execution-staged-activation.plan-blocked.valid.json \
  packages/contracts/fixtures/execution-staged-activation.states.valid.json \
  packages/contracts/openapi/execution-staged-activation.openapi.json \
  packages/contracts/generated/execution-staged-activation.d.ts \
  packages/contracts/fixtures/execution-analytics.insight-batch.valid.json \
  packages/contracts/fixtures/execution-analytics.correlation.valid.json \
  packages/contracts/fixtures/execution-analytics.capital-ledger.valid.json \
  packages/contracts/fixtures/execution-analytics.binding-exposure.valid.json \
  packages/contracts/fixtures/execution-projection-page.valid.json \
  packages/contracts/fixtures/execution-governance.r2-review.valid.json \
  packages/contracts/fixtures/execution-governance.paper-exit-review.valid.json \
  packages/contracts/fixtures/execution-realtime.auth-expiring.valid.json \
  packages/contracts/fixtures/execution-realtime.projection-gap.valid.json \
  packages/contracts/fixtures/execution-analytics.equity-projection.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-line.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-histogram.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-funnel.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-waterfall.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-heatmap.valid.json \
  packages/contracts/fixtures/execution-analytics.insight-bar.valid.json \
  packages/contracts/fixtures/execution-events.corpus.valid.json \
  packages/contracts/fixtures/execution-command-catalog.valid.json \
  packages/contracts/fixtures/execution-command-plan.valid.json \
  packages/contracts/fixtures/execution-command-operation.valid.json \
  packages/contracts/fixtures/execution-command-relay-denied.valid.json \
  packages/contracts/fixtures/execution-operations-queue.valid.json \
  packages/contracts/fixtures/execution-operation-workflow.valid.json \
  packages/contracts/fixtures/execution-incident-detail.open.valid.json \
  packages/contracts/fixtures/execution-incident-workflow.resolved.valid.json \
  packages/contracts/generated/portal-api.d.ts \
  packages/contracts/generated/execution-analytics.d.ts \
  packages/contracts/generated/execution-analytics-series.d.ts \
  packages/contracts/generated/execution-governance.d.ts \
  packages/contracts/generated/execution-realtime.d.ts \
  packages/contracts/generated/execution-operations.d.ts \
  packages/contracts/openapi/execution-analytics.openapi.json \
  packages/contracts/openapi/execution-analytics-series.openapi.json \
  packages/contracts/openapi/execution-governance.openapi.json \
  packages/contracts/openapi/execution-realtime.openapi.json \
  packages/contracts/openapi/execution-operations.openapi.json \
  packages/contracts/tooling/generate-execution-command-catalog.mjs \
  packages/contracts/vitest.config.ts \
  packages/contracts/test/fixtures.spec.ts \
  scripts/contracts-test.sh \
  upgrade/backend/BAR_06_SHARED_CONTRACT_AUTHORITY.md \
  upgrade/backend/adr/ADR-001-JAVASCRIPT_WORKSPACE_AND_LOCK_AUTHORITY.md \
  upgrade/backend/adr/ADR-002-OPAQUE_ID_FORMAT.md \
  upgrade/backend/adr/ADR-005-EVENT_SCHEMA_ENCODING_AND_REGISTRY.md \
  apps/portal/backend/tests/test_m0_freeze.py \
  apps/portal/scripts/export_m0_freeze.py \
  apps/portal/scripts/export_environment_report.py \
  scripts/verify-m0-golden.sh \
  upgrade/backend/BAR_05_REPRODUCIBILITY_FREEZE.md \
  upgrade/backend/bar05/m0-freeze-manifest.json \
  upgrade/backend/bar05/environment-report.json \
  apps/portal/backend/tests/test_frontend_handoff.py \
  apps/portal/backend/tests/test_compat_parity.py \
  apps/portal/backend/tests/test_artifact_provenance.py \
  apps/portal/backend/tests/test_portal_links_api.py \
  apps/portal/backend/tests/test_ingress_boundary.py \
  apps/portal/frontend/package-lock.json \
  apps/portal/registry/registry.json \
  apps/portal/registry/links.v1.json \
  apps/portal/registry/fixtures/links.public.json \
  apps/portal/registry/FRONTEND_HANDOFF.md \
  apps/portal/registry/openapi/portal-api.openapi.json \
  apps/portal/registry/fixtures/registry.public.json \
  apps/portal/registry/fixtures/summary.healthy.json \
  apps/portal/registry/fixtures/summary.empty.json \
  apps/portal/registry/fixtures/summary.partial.json \
  apps/portal/registry/fixtures/summary.stale.json \
  apps/portal/registry/fixtures/summary.denied.json \
  apps/portal/registry/fixtures/summary.unavailable.json \
  apps/portal/scripts/export_handoff_contract.py \
  apps/portal/scripts/export_compat_snapshots.py \
  apps/portal/registry/schemas/portal-registry-source.v1.schema.json \
  apps/portal/registry/schemas/portal-registry.v1.schema.json \
  apps/portal/registry/schemas/portal-summary.v1.schema.json \
  apps/portal/registry/schemas/portal-links.v1.schema.json \
  apps/portal/strategy/PROTECTED_SHA256 \
  upgrade/backend/BAR_02_COMPATIBILITY_BOUNDARIES_AND_PARITY_FREEZE.md \
  upgrade/backend/BAR_03_OPERATIONAL_INGRESS_BOUNDARY.md \
  deploy/cloudflared/config.example.yml \
  deploy/nginx/portal-loopback.conf \
  deploy/edge/README.md \
  docs/release-and-deployment.md \
  .github/workflows/ci.yml \
  .github/workflows/deploy.yml \
  scripts/verify-migration-history.sh \
  scripts/verify-release-channel.sh \
  deploy/nginx/portal.conf \
  apps/control-api/package.json \
  apps/control-api/package-lock.json \
  apps/control-api/tsconfig.json \
  apps/control-api/vitest.config.ts \
  apps/control-api/migrations/1723680000000_init-identity.sql \
  apps/control-api/migrations/1723680000001_control-facade.sql \
  apps/control-api/migrations/1723680000002_execution-governance.sql \
  apps/control-api/migrations/1723680000003_execution-approval-analytics-scope.sql \
  apps/control-api/migrations/1723680000004_governance-paper-exit.sql \
  apps/control-api/migrations/1723680000005_command-center-pins.sql \
  apps/control-api/migrations/1723680000006_execution-operations-f0.sql \
  apps/control-api/migrations/1723680000007_execution-operations-f0-hardening.sql \
  apps/control-api/migrations/1723680000008_execution-operations-queue.sql \
  apps/control-api/migrations/1723680000009_execution-incidents.sql \
  apps/control-api/src/id.ts \
  apps/control-api/src/repos/workspaces.ts \
  apps/control-api/src/repos/runs.ts \
  apps/control-api/src/repos/outbox.ts \
  apps/control-api/src/facade/proxy.service.ts \
  apps/control-api/src/facade/facade.controller.ts \
  apps/control-api/src/facade/session.guard.ts \
  apps/control-api/src/query/contracts.ts \
  apps/control-api/src/query/cursor.ts \
  apps/control-api/src/query/index.ts \
  apps/control-api/src/query/postgres.ts \
  apps/control-api/src/query/request.ts \
  apps/control-api/test/query.spec.ts \
  upgrade/backend/EX_BE_04A_CONTROL_PLANE_QUERY_PRIMITIVES.md \
  apps/control-api/src/governance/apply-token.ts \
  apps/control-api/src/governance/contracts.ts \
  apps/control-api/src/governance/governance.controller.ts \
  apps/control-api/src/governance/governance.repository.ts \
  apps/control-api/src/governance/governance.service.ts \
  apps/control-api/src/governance/paper-exit.repository.ts \
  apps/control-api/src/governance/paper-exit.service.ts \
  apps/control-api/test/governance-token.spec.ts \
  apps/control-api/test/governance.spec.ts \
  apps/control-api/test/paper-exit.spec.ts \
  apps/control-api/src/operations/contracts.ts \
  apps/control-api/src/operations/catalog.generated.ts \
  apps/control-api/src/operations/operations.repository.ts \
  apps/control-api/src/operations/operations.service.ts \
  apps/control-api/src/operations/workflow.repository.ts \
  apps/control-api/src/operations/workflow.service.ts \
  apps/control-api/test/execution-operations.spec.ts \
  apps/control-api/src/operations/incident.controller.ts \
  apps/control-api/src/operations/incident.repository.ts \
  apps/control-api/src/operations/incident.service.ts \
  apps/control-api/test/incident-workflow.spec.ts \
  upgrade/backend/EX_BE_05B_F0_OFFLINE_OPERATIONS_FOUNDATION.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F0_HANDOFF.md \
  upgrade/backend/EX_BE_05B_F1A_OPERATIONS_QUEUE.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F1A_HANDOFF.md \
  upgrade/backend/EX_BE_05B_F1B_INCIDENT_DETAIL.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_EX_BE_05B_F1B_HANDOFF.md \
  upgrade/backend/EX_BE_05A_GOVERNANCE_EVIDENCE_APPROVAL.md \
  services/portal-execution-edge-rs/Cargo.toml \
  services/portal-execution-edge-rs/Cargo.lock \
  services/portal-execution-edge-rs/crates/external-read-adapter/Cargo.toml \
  services/portal-execution-edge-rs/crates/external-read-adapter/src/lib.rs \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/README.md \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/capability-catalogue.schema.json \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/capability-catalogue.example.json \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/semantic-rulings.example.json \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/golden-corpus-index.example.json \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/acceptance-results.example.json \
  services/portal-execution-edge-rs/contracts/n11-external-read-v1-request/owner-publication.manifest.example.json \
  scripts/execution-n11-external-read-verify.py \
  scripts/test_execution_n11_external_read_verify.py \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/README.md \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/command-capability-catalogue.schema.json \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/command-capability-catalogue.example.json \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/terminal-corpus-index.example.json \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/acceptance-results.example.json \
  services/portal-execution-edge-rs/contracts/n12-command-relay-v1-request/owner-publication.manifest.example.json \
  scripts/execution-n12-command-publication-verify.py \
  scripts/test_execution_n12_command_publication_verify.py \
  services/portal-execution-edge-rs/rust-toolchain.toml \
  services/portal-execution-edge-rs/contract-pack.lock.json \
  services/portal-execution-edge-rs/crates/execution-contracts/src/lib.rs \
  services/portal-execution-edge-rs/crates/execution-contracts/src/events.rs \
  services/portal-execution-edge-rs/crates/analytics/src/series.rs \
  services/portal-execution-edge-rs/crates/analytics/src/tiles.rs \
  services/portal-execution-edge-rs/crates/ts-contract-v1/src/lib.rs \
  services/portal-execution-edge-rs/crates/ts-adapter-v1/src/lib.rs \
  services/portal-execution-edge-rs/crates/command-relay/Cargo.toml \
  services/portal-execution-edge-rs/crates/command-relay/src/lib.rs \
  services/portal-execution-edge-rs/crates/edge-service/src/d4_command.rs \
  services/portal-execution-edge-rs/crates/projection-core/Cargo.toml \
  services/portal-execution-edge-rs/crates/projection-core/src/lib.rs \
  services/portal-execution-edge-rs/crates/query-api/Cargo.toml \
  services/portal-execution-edge-rs/crates/query-api/src/lib.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/Cargo.toml \
  services/portal-execution-edge-rs/crates/projection-store-pg/src/lib.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/src/d4_writer.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/src/query.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/src/analytics_repository.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/src/shared_consumer.rs \
  services/portal-execution-edge-rs/crates/shared-consumer-core/Cargo.toml \
  services/portal-execution-edge-rs/crates/shared-consumer-core/src/lib.rs \
  services/portal-execution-edge-rs/crates/shared-consumer-core/src/tests.rs \
  services/portal-execution-edge-rs/crates/shared-consumer-core/fixtures/redacted-snapshots.json \
  services/portal-execution-edge-rs/crates/paper-shadow-mapper/Cargo.toml \
  services/portal-execution-edge-rs/crates/paper-shadow-mapper/src/lib.rs \
  services/portal-execution-edge-rs/crates/paper-shadow-mapper/src/tests.rs \
  services/portal-execution-edge-rs/fixtures/d4-paper-shadow-corpus.manifest.json \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0001_projection_foundation.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0002_projection_query_foundation.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0003_analytics_source_projection.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0004_analytics_integrity_hardening.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0005_projection_event_entity.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0006_projection_operation_and_sequence_semantics.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0007_d4_source_checkpoint.sql \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0008_shared_consumer_lease.sql \
  services/portal-execution-edge-rs/crates/paper-source-contract/Cargo.toml \
  services/portal-execution-edge-rs/crates/paper-source-contract/build.rs \
  services/portal-execution-edge-rs/crates/paper-source-contract/src/lib.rs \
  services/portal-execution-edge-rs/crates/paper-source-contract/src/tests.rs \
  services/portal-execution-edge-rs/crates/paper-source-ingestor/Cargo.toml \
  services/portal-execution-edge-rs/crates/paper-source-ingestor/src/lib.rs \
  services/portal-execution-edge-rs/crates/paper-source-ingestor/src/tests.rs \
  services/portal-execution-edge-rs/crates/paper-source-runner/Cargo.toml \
  services/portal-execution-edge-rs/crates/paper-source-runner/src/lib.rs \
  services/portal-execution-edge-rs/crates/paper-source-runner/src/tests.rs \
  services/portal-execution-edge-rs/crates/paper-source-transport/Cargo.toml \
  services/portal-execution-edge-rs/crates/paper-source-transport/src/lib.rs \
  services/portal-execution-edge-rs/crates/paper-source-transport/src/tests.rs \
  deploy/images/execution-edge-ci.Dockerfile \
  deploy/images/source-proxy.Dockerfile \
  scripts/execution-edge-test.sh \
  scripts/execution-offline-hardening-test.sh \
  scripts/execution-d1-preflight.sh \
  scripts/execution-d1-open-window.sh \
  scripts/execution-d1-render-wireguard.sh \
  scripts/execution-d1-test.sh \
  scripts/execution-iam-verify.py \
  scripts/test_execution_iam_verify.py \
  scripts/execution-d2-host-admission.py \
  scripts/test_execution_d2_host_admission.py \
  scripts/execution-d2-authorization.py \
  scripts/test_execution_d2_authorization.py \
  scripts/execution-d2-isolation.py \
  scripts/test_execution_d2_isolation.py \
  scripts/execution-d2-preflight.sh \
  scripts/execution-d2-render-source-proxy.sh \
  scripts/execution-d2-test.sh \
  scripts/execution-d3-render-probe-env.sh \
  scripts/execution-d3-live-probe.sh \
  scripts/execution-d3-test.sh \
  scripts/execution-d4-authorization.py \
  scripts/test_execution_d4_authorization.py \
  scripts/execution-d4-dormant-closeout.py \
  scripts/test_execution_d4_dormant_closeout.py \
  scripts/execution-n02-contract-verify.py \
  scripts/test_execution_n02_contract_verify.py \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/README.md \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/owner-pack.manifest.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.schema.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/compatibility-fixtures.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/error-corpus.example.json \
  scripts/execution-n03-implementation-verify.py \
  scripts/test_execution_n03_implementation_verify.py \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/README.md \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/owner-implementation.manifest.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/implementation-profile.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/source-metrics.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/query-plan-evidence.example.json \
  services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/acceptance-results.example.json \
  scripts/execution-image-publication-test.sh \
  scripts/execution-tracking-test.sh \
  .github/workflows/publish-images.yml \
  deploy/execution-d1/README.md \
  deploy/execution-d1/owner-input.env.example \
  deploy/execution-d1/edge-source-proxy.env.example \
  deploy/execution-d1/compose.dark.yaml \
  deploy/execution-d1/wireguard/portal0.sgp.conf.template \
  deploy/execution-d1/wireguard/portal0.aws.conf.template \
  deploy/execution-d1/pki/openssl-workload-profiles.cnf.template \
  deploy/execution-d1/pki/identity-inventory.md \
  deploy/execution-d1/source-proxy/nginx.conf.template \
  deploy/execution-d1/source-proxy/trading-system-read-header.conf.example \
  deploy/runbooks/execution-d1-bootstrap-and-rollback.md \
  deploy/execution-d2/README.md \
  deploy/execution-d2/owner-input.env.example \
  deploy/execution-d2/init-projection-database.sh \
  deploy/runbooks/execution-d2-dark-deploy-and-rollback.md \
  upgrade/backend/EX_BE_02_LIVE_D2_AUTHORIZATION_CONTRACT.md \
  upgrade/backend/EX_BE_02_D2_PLACEMENT_DECISION.md \
  deploy/execution-d3/README.md \
  deploy/execution-d3/compose.probes.yaml \
  deploy/runbooks/execution-d3-contract-auth-probes-and-rollback.md \
  deploy/execution-d4/README.md \
  deploy/execution-d4/owner-input.env.example \
  deploy/execution-d4/qualification-runtime.env.example \
  deploy/execution-d4/storage-input.env.example \
  deploy/execution-d4/dormant-closeout.env.example \
  deploy/execution-d4/source-idle-evidence.json.example \
  deploy/execution-d4/systemd/portal-execution-d4-window-guard.service.example \
  deploy/execution-d4/compose.encrypted-storage.yaml \
  deploy/execution-d4/compose.paper-read-shadow.yaml \
  deploy/execution-d4/source-proxy/nginx.conf.template \
  deploy/execution-d4/source-proxy/trading-system-read-header.conf.example \
  deploy/runbooks/execution-d4-paper-shadow-and-rollback.md \
  scripts/execution-d4-storage-preflight.sh \
  scripts/execution-d4-render-source-proxy.sh \
  scripts/execution-d4-source-proxy-preflight.sh \
  scripts/execution-d4-qualification-preflight.sh \
  scripts/execution-d4-qualification-preflight-test.sh \
  scripts/execution-d4-source-proxy-test.sh \
  scripts/test-execution-d4-storage.sh \
  upgrade/backend/EX_BE_02_LIVE_D4_SOURCE_PROXY_OFFLINE.md \
  upgrade/backend/EX_BE_02_LIVE_D4_QUALIFICATION_RUNTIME_ENTRYPOINT.md \
  upgrade/backend/EX_BE_02_LIVE_D4_OFFLINE_AUTHORIZATION_PREPARATION.md \
  upgrade/backend/EX_BE_02_LIVE_D4_READINESS_AUDIT_AND_OWNER_REQUEST.md \
  upgrade/backend/EX_BE_02_LIVE_D4_MAPPER_CORE_HARDENING.md \
  upgrade/backend/EX_BE_02_LIVE_D4_ENCRYPTED_STORAGE_BOUNDARY.md \
  upgrade/backend/EX_BE_02_LIVE_D4_OWNER_ACTION_PACKET.md \
  upgrade/backend/EX_BE_02_D4_DORMANT_CLOSEOUT_DISCIPLINE.md \
  upgrade/backend/EX_BE_02_N02_INCREMENTAL_SOURCE_CONTRACT_REVISION.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N02_INCREMENTAL_SOURCE_CONTRACT_HANDOFF.md \
  upgrade/backend/EX_BE_02_N03_TRADING_SYSTEM_INCREMENTAL_SOURCE_IMPLEMENTATION.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N03_OWNER_IMPLEMENTATION_HANDOFF.md \
  upgrade/backend/EX_BE_03_N04_LEASE_AWARE_RUST_SHARED_CONSUMER.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N04_LEASE_AWARE_CONSUMER_HANDOFF.md \
  upgrade/backend/EX_BE_03_N05_RETENTION_RECOVERY_CLEANUP.md \
  upgrade/backend/EX_BE_03_N06_REAL_SOURCE_QUALIFICATION_AND_SOAK.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N06_REAL_SOURCE_QUALIFICATION_HANDOFF.md \
  upgrade/backend/EX_BE_03_N07_PROJECTION_QUERY_ANALYTICS_SHADOW.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N07_SHADOW_SCREEN_APIS_HANDOFF.md \
  services/portal-execution-edge-rs/crates/source-qualification/src/real_source.rs \
  services/portal-execution-edge-rs/crates/source-qualification/src/real_source_tests.rs \
  services/portal-execution-edge-rs/crates/source-qualification/src/bin/n06_verify.rs \
  services/portal-execution-edge-rs/crates/source-qualification/fixtures/n06-real-source-qualification.template.json \
  services/portal-execution-edge-rs/crates/source-qualification/src/shadow_screen.rs \
  services/portal-execution-edge-rs/crates/projection-store-pg/migrations/0010_shadow_screen_activation.sql \
  packages/contracts/fixtures/execution-paper-workbench.orders-shadow.valid.json \
  scripts/execution-n06-qualification-verify.sh \
  scripts/execution-n06-qualification-test.sh \
  upgrade/backend/EX_BE_02_LIVE_D1_OFFLINE_PREPARATION.md \
  upgrade/backend/EX_BE_02_LIVE_D1_EXECUTION_EVIDENCE.md \
  upgrade/backend/EX_BE_02_LIVE_IAM_VERIFICATION_AND_D1_REVALIDATION.md \
  upgrade/backend/EX_BE_02_LIVE_D2_ADMISSION_CHECKPOINT.md \
  upgrade/backend/EX_BE_02_LIVE_D3_OFFLINE_PREPARATION.md \
  upgrade/backend/EX_BE_01_RUST_CONTRACTS_AND_TS_ADAPTER.md \
  upgrade/backend/EX_BE_03_PROJECTION_REDUCER_REPLAY_FRESHNESS.md \
  upgrade/backend/EX_BE_04B_RUST_PROJECTION_QUERY_PRIMITIVES.md \
  upgrade/backend/EX_BE_07B_SOURCE_BACKED_PROJECTION_REPOSITORIES_AND_SCREEN_APIS.md \
  upgrade/backend/PRE_IAM_06_TRACKING_RECONCILIATION_CLOSEOUT.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/EXECUTION_REQUEST_LEDGER.md \
  upgrade/backend/adr/ADR-007-PORTAL-PROJECTION-EPOCH-CURSOR-AND-FRESHNESS.md \
  apps/control-api/test/facade.spec.ts \
  upgrade/backend/BAR_07_CONTROL_API_FACADE.md \
  apps/control-api/src/main.ts \
  apps/control-api/src/app.ts \
  apps/control-api/src/app.module.ts \
  apps/control-api/src/config.ts \
  apps/control-api/test/config.spec.ts \
  apps/control-api/src/domain.ts \
  apps/control-api/src/tokens.ts \
  apps/control-api/src/http-error.filter.ts \
  apps/control-api/src/execution/analytics.controller.ts \
  apps/control-api/src/execution/analytics.proxy.ts \
  apps/control-api/test/execution-analytics.spec.ts \
  apps/control-api/migrations/1723680000013_execution-staged-activation.sql \
  apps/control-api/src/activation/contracts.ts \
  apps/control-api/src/activation/activation.repository.ts \
  apps/control-api/src/activation/activation.service.ts \
  apps/control-api/src/activation/activation.controller.ts \
  apps/control-api/test/staged-activation.spec.ts \
  upgrade/backend/EX_BE_08_N13A_SOURCE_DARK_STAGED_ACTIVATION.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N13A_STAGED_ACTIVATION_HANDOFF.md \
  upgrade/backend/EX_BE_17_N14A_PORTAL_RELEASE_AUTHORITY_SOURCE_DARK.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N14A_RELEASE_AUTHORITY_HANDOFF.md \
  upgrade/backend/EX_BE_18_N15A_SOURCE_DARK_FOUR_INTERFACE_GATEWAY.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N15A_FOUR_INTERFACE_GATEWAY_HANDOFF.md \
  packages/contracts/schemas/execution-intercell-gateway.v1.schema.json \
  packages/contracts/fixtures/execution-intercell-gateway.source-dark.valid.json \
  packages/contracts/fixtures/execution-intercell-gateway.event-corpus.valid.json \
  packages/contracts/fixtures/execution-intercell-gateway.artifact-corpus.valid.json \
  packages/contracts/openapi/execution-intercell-gateway.openapi.json \
  packages/contracts/generated/execution-intercell-gateway.d.ts \
  services/portal-execution-edge-rs/crates/intercell-gateway/Cargo.toml \
  services/portal-execution-edge-rs/crates/intercell-gateway/src/lib.rs \
  scripts/execution-n15a-gateway-test.sh \
  upgrade/backend/EX_BE_19_N16A_SOURCE_DARK_ROUTING_AND_EMERGENCY_POLICY.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N16A_EMERGENCY_ROUTING_HANDOFF.md \
  packages/contracts/schemas/execution-emergency-routing.v1.schema.json \
  packages/contracts/fixtures/execution-emergency-routing.source-dark.valid.json \
  packages/contracts/fixtures/execution-emergency-routing.ui-corpus.valid.json \
  packages/contracts/openapi/execution-emergency-routing.openapi.json \
  packages/contracts/generated/execution-emergency-routing.d.ts \
  services/portal-execution-edge-rs/crates/emergency-routing/Cargo.toml \
  services/portal-execution-edge-rs/crates/emergency-routing/src/lib.rs \
  deploy/execution-emergency/README.md \
  deploy/execution-emergency/origin-isolation.source-dark.json \
  deploy/execution-emergency/nginx.same-origin.source-dark.conf.template \
  scripts/execution-n16a-emergency-routing-test.sh \
  upgrade/backend/EX_BE_20_N17A_SOURCE_DARK_PRODUCTION_DR_PREPARATION.md \
  upgrade/upgrade_frontend_plan_hifi/hifi_execution_loop/CODEX_TO_CLAUDE_N17A_PRODUCTION_READINESS_HANDOFF.md \
  packages/contracts/schemas/execution-production-readiness.v1.schema.json \
  packages/contracts/fixtures/execution-production-readiness.source-dark.valid.json \
  packages/contracts/fixtures/execution-production-readiness.game-day-corpus.valid.json \
  packages/contracts/openapi/execution-production-readiness.openapi.json \
  packages/contracts/generated/execution-production-readiness.d.ts \
  services/portal-execution-edge-rs/crates/production-readiness/Cargo.toml \
  services/portal-execution-edge-rs/crates/production-readiness/src/lib.rs \
  deploy/execution-readiness/README.md \
  deploy/execution-readiness/slo-alerts.source-dark.yml \
  deploy/execution-readiness/grafana-dashboard.source-dark.json \
  deploy/execution-readiness/capacity-retention-cost.source-dark.json \
  deploy/execution-readiness/rotation-inventory.source-dark.json \
  deploy/execution-readiness/owner-matrix.source-dark.json \
  deploy/execution-readiness/game-day-plan.source-dark.json \
  deploy/runbooks/portal-n17a-source-dark-production-dr.md \
  scripts/execution-n17a-readiness.py \
  scripts/test_execution_n17a_readiness.py \
  scripts/execution-n17a-production-dr-test.sh \
  deploy/.env.development.example \
  deploy/manifests/deployment-profile.v1.schema.json \
  deploy/manifests/deployment-profiles.source-dark.json \
  deploy/manifests/portal-release-compatibility-matrix.v1.schema.json \
  deploy/manifests/compatibility-matrix.source-dark.json \
  deploy/manifests/portal-release-manifest.v1.schema.json \
  deploy/manifests/portal-release-candidate-evidence.v1.schema.json \
  deploy/manifests/portal-release-owner-decision.v1.schema.json \
  deploy/manifests/release-manifest.template.json \
  deploy/manifests/release-candidate-evidence.template.json \
  deploy/manifests/release-owner-decision.template.json \
  deploy/runbooks/portal-n14a-source-dark-release-and-rollback.md \
  scripts/portal-release-authority.py \
  scripts/test_portal_release_authority.py \
  scripts/portal-release-authority-test.sh \
  apps/control-api/src/auth/auth.service.ts \
  apps/control-api/src/auth/auth.controller.ts \
  apps/control-api/src/auth/argon.ts \
  apps/control-api/src/auth/policy.ts \
  apps/control-api/src/auth/cloudflare.ts \
  apps/control-api/src/auth/principal.ts \
  apps/control-api/src/auth/cookies.ts \
  apps/control-api/src/admin/admin.service.ts \
  apps/control-api/src/admin/admin.controller.ts \
  apps/control-api/src/admin/rbac.guard.ts \
  apps/control-api/src/repos/users.ts \
  apps/control-api/src/repos/bindings.ts \
  apps/control-api/src/repos/credentials.ts \
  apps/control-api/src/repos/sessions.ts \
  apps/control-api/src/repos/audit.ts \
  apps/control-api/src/db/pool.ts \
  apps/control-api/src/health/health.controller.ts \
  apps/control-api/src/cli/bootstrap.ts \
  apps/control-api/test/health.spec.ts \
  apps/control-api/test/harness.ts \
  apps/control-api/test/repos.spec.ts \
  apps/control-api/test/auth.spec.ts \
  apps/control-api/test/matrix.spec.ts \
  deploy/images/control-api.Dockerfile \
  scripts/control-api-test.sh \
  scripts/control-api-provision-keyrings.sh \
  upgrade/backend/BAR_04_THIN_IDENTITY_BFF.md \
  upgrade/backend/adr/ADR-003-POSTGRES_MIGRATION_AND_QUERY_APPROACH.md \
  upgrade/backend/bar02/snapshots/portal-api.openapi.json \
  upgrade/backend/bar02/snapshots/planning-api.openapi.json \
  upgrade/backend/bar02/snapshots/run-request.schema.json \
  upgrade/backend/bar02/snapshots/manifest.json \
  features/roadmap-task-board/backend/requirements-dev.txt \
  features/roadmap-task-board/backend/tests/test_summary_contract.py \
  features/roadmap-task-board/frontend/package-lock.json; do
  git -C "${ROOT_DIR}" ls-files --error-unmatch "${tracked_source}" >/dev/null || {
    printf 'Portal source is present but not tracked by the parent Git: %s\n' "${tracked_source}" >&2
    exit 1
  }
done

command -v python3 >/dev/null 2>&1 || {
  printf 'Python 3 is required to validate Portal JSON contracts.\n' >&2
  exit 1
}

for json_contract in \
  "${ROOT_DIR}/apps/portal/registry/registry.json" \
  "${ROOT_DIR}/deploy/manifests/deployment-profile.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/deployment-profiles.source-dark.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-compatibility-matrix.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/compatibility-matrix.source-dark.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-manifest.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-candidate-evidence.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/portal-release-owner-decision.v1.schema.json" \
  "${ROOT_DIR}/deploy/manifests/release-manifest.template.json" \
  "${ROOT_DIR}/deploy/manifests/release-candidate-evidence.template.json" \
  "${ROOT_DIR}/deploy/manifests/release-owner-decision.template.json" \
  "${ROOT_DIR}/deploy/execution-d4/source-idle-evidence.json.example" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/owner-pack.manifest.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/incremental-contract.schema.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/compatibility-fixtures.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-request/error-corpus.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/owner-implementation.manifest.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/implementation-profile.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/source-metrics.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/query-plan-evidence.example.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contracts/d4-paper-read-v2-implementation-request/acceptance-results.example.json" \
  "${ROOT_DIR}/apps/portal/registry/links.v1.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-registry-source.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-registry.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-summary.v1.schema.json" \
  "${ROOT_DIR}/apps/portal/registry/schemas/portal-links.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/keyset-page.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/keyset-page.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.capital-preview.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.order-funnel.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-batch.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.correlation.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.capital-ledger.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.binding-exposure.valid.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-analytics-series.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-event-envelope.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.equity-projection.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-line.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-histogram.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-funnel.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-waterfall.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-heatmap.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-analytics.insight-bar.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-events.corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-analytics-series.openapi.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-projection-page.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-projection-page.valid.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-governance-r2-review.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-governance-paper-exit.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.r2-review.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-governance.paper-exit-review.valid.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-realtime-event.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-realtime.auth-expiring.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-realtime.projection-gap.valid.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-operations.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-intercell-gateway.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.event-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-intercell-gateway.artifact-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/schemas/execution-emergency-routing.v1.schema.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-emergency-routing.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-emergency-routing.ui-corpus.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-catalog.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-plan.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-operation.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-command-relay-denied.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-operations-queue.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-operation-workflow.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-incident-detail.open.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-incident-workflow.resolved.valid.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-analytics.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-governance.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-realtime.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-operations.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-intercell-gateway.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-emergency-routing.openapi.json" \
  "${ROOT_DIR}/packages/contracts/openapi/execution-production-readiness.openapi.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-production-readiness.source-dark.valid.json" \
  "${ROOT_DIR}/packages/contracts/fixtures/execution-production-readiness.game-day-corpus.valid.json" \
  "${ROOT_DIR}/deploy/execution-readiness/grafana-dashboard.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/capacity-retention-cost.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/rotation-inventory.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/owner-matrix.source-dark.json" \
  "${ROOT_DIR}/deploy/execution-readiness/game-day-plan.source-dark.json" \
  "${ROOT_DIR}/services/portal-execution-edge-rs/contract-pack.lock.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/planning-api.openapi.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/run-request.schema.json" \
  "${ROOT_DIR}/upgrade/backend/bar02/snapshots/manifest.json"; do
  python3 -m json.tool "${json_contract}" >/dev/null
done

bash -n \
  "${ROOT_DIR}/scripts/portal" \
  "${ROOT_DIR}/scripts/verify-workspace.sh" \
  "${ROOT_DIR}/scripts/verify-migration-history.sh" \
  "${ROOT_DIR}/scripts/verify-release-channel.sh" \
  "${ROOT_DIR}/scripts/portal-release-authority-test.sh" \
  "${ROOT_DIR}/scripts/execution-n16a-emergency-routing-test.sh" \
  "${ROOT_DIR}/scripts/execution-n17a-production-dr-test.sh" \
  "${ROOT_DIR}/scripts/build-trading-system-owner-campaign-pack.sh" \
  "${ROOT_DIR}/scripts/smoke-stack.sh" \
  "${ROOT_DIR}/scripts/control-api-provision-keyrings.sh" \
  "${ROOT_DIR}/scripts/stage-hmd-reader-wheel.sh" \
  "${ROOT_DIR}/scripts/install-git-hooks.sh" \
  "${ROOT_DIR}/scripts/provision-contributor-workspace.sh" \
  "${ROOT_DIR}/scripts/verify-contributor-workspace.sh" \
  "${ROOT_DIR}/.githooks/lib/access-policy.sh" \
  "${ROOT_DIR}/.githooks/pre-applypatch" \
  "${ROOT_DIR}/.githooks/pre-commit" \
  "${ROOT_DIR}/.githooks/pre-merge-commit" \
  "${ROOT_DIR}/.githooks/pre-push" \
  "${ROOT_DIR}/.githooks/pre-rebase" \
  "${ROOT_DIR}/apps/portal/scripts/run_backend.sh" \
  "${ROOT_DIR}/apps/portal/scripts/run_dev.sh" \
  "${ROOT_DIR}/apps/portal/scripts/run_frontend.sh" \
  "${ROOT_DIR}/scripts/verify-m0-golden.sh" \
  "${ROOT_DIR}/scripts/execution-edge-test.sh" \
  "${ROOT_DIR}/scripts/execution-offline-hardening-test.sh" \
  "${ROOT_DIR}/scripts/execution-edge-live-probe.sh" \
  "${ROOT_DIR}/scripts/execution-d1-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d1-open-window.sh" \
  "${ROOT_DIR}/scripts/execution-d1-render-wireguard.sh" \
  "${ROOT_DIR}/scripts/execution-d1-test.sh" \
  "${ROOT_DIR}/scripts/execution-d2-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d2-render-source-proxy.sh" \
  "${ROOT_DIR}/scripts/execution-d2-test.sh" \
  "${ROOT_DIR}/scripts/execution-d3-render-probe-env.sh" \
  "${ROOT_DIR}/scripts/execution-d3-live-probe.sh" \
  "${ROOT_DIR}/scripts/execution-d3-test.sh" \
  "${ROOT_DIR}/scripts/execution-d4-storage-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-render-source-proxy.sh" \
  "${ROOT_DIR}/scripts/execution-d4-source-proxy-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-qualification-preflight.sh" \
  "${ROOT_DIR}/scripts/execution-d4-qualification-preflight-test.sh" \
  "${ROOT_DIR}/scripts/execution-d4-source-proxy-test.sh" \
  "${ROOT_DIR}/scripts/test-execution-d4-storage.sh" \
  "${ROOT_DIR}/scripts/execution-n06-qualification-verify.sh" \
  "${ROOT_DIR}/scripts/execution-n06-qualification-test.sh" \
  "${ROOT_DIR}/scripts/execution-image-publication-test.sh" \
  "${ROOT_DIR}/scripts/execution-n15a-gateway-test.sh" \
  "${ROOT_DIR}/scripts/execution-n16a-emergency-routing-test.sh" \
  "${ROOT_DIR}/scripts/execution-n17a-production-dr-test.sh" \
  "${ROOT_DIR}/scripts/execution-tracking-test.sh" \
  "${ROOT_DIR}/deploy/execution-d2/init-projection-database.sh" \
  "${ROOT_DIR}/apps/portal/scripts/smoke_quantbt_pypi.sh" \
  "${ROOT_DIR}/apps/portal/scripts/test_backend.sh" \
  "${ROOT_DIR}/features/roadmap-task-board/tooling/clean-generated.sh"

(cd "${ROOT_DIR}/apps/portal" && sha256sum -c strategy/PROTECTED_SHA256)
python3 -m py_compile \
  "${ROOT_DIR}/scripts/execution-iam-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_iam_verify.py" \
  "${ROOT_DIR}/scripts/execution-d2-host-admission.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_host_admission.py" \
  "${ROOT_DIR}/scripts/execution-d2-authorization.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_authorization.py" \
  "${ROOT_DIR}/scripts/execution-d2-isolation.py" \
  "${ROOT_DIR}/scripts/test_execution_d2_isolation.py" \
  "${ROOT_DIR}/scripts/execution-d4-authorization.py" \
  "${ROOT_DIR}/scripts/test_execution_d4_authorization.py" \
  "${ROOT_DIR}/scripts/execution-d4-dormant-closeout.py" \
  "${ROOT_DIR}/scripts/test_execution_d4_dormant_closeout.py" \
  "${ROOT_DIR}/scripts/execution-n02-contract-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n02_contract_verify.py" \
  "${ROOT_DIR}/scripts/execution-n03-implementation-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n03_implementation_verify.py" \
  "${ROOT_DIR}/scripts/execution-n11-external-read-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n11_external_read_verify.py" \
  "${ROOT_DIR}/scripts/execution-n12-command-publication-verify.py" \
  "${ROOT_DIR}/scripts/test_execution_n12_command_publication_verify.py"
python3 -m py_compile \
  "${ROOT_DIR}/scripts/portal-release-authority.py" \
  "${ROOT_DIR}/scripts/test_portal_release_authority.py" \
  "${ROOT_DIR}/scripts/execution-n17a-readiness.py" \
  "${ROOT_DIR}/scripts/test_execution_n17a_readiness.py"
python3 "${ROOT_DIR}/scripts/test_execution_iam_verify.py"
python3 "${ROOT_DIR}/scripts/test_execution_d2_host_admission.py"
python3 "${ROOT_DIR}/scripts/test_execution_d2_authorization.py"
python3 "${ROOT_DIR}/scripts/test_execution_d2_isolation.py"
python3 "${ROOT_DIR}/scripts/test_execution_d4_authorization.py"
python3 "${ROOT_DIR}/scripts/test_execution_d4_dormant_closeout.py"
python3 "${ROOT_DIR}/scripts/execution-n02-contract-verify.py" --mode template
python3 "${ROOT_DIR}/scripts/test_execution_n02_contract_verify.py"
python3 "${ROOT_DIR}/scripts/execution-n03-implementation-verify.py" --mode template
python3 "${ROOT_DIR}/scripts/test_execution_n03_implementation_verify.py"
python3 "${ROOT_DIR}/scripts/execution-n11-external-read-verify.py" --mode template
python3 "${ROOT_DIR}/scripts/test_execution_n11_external_read_verify.py"
python3 "${ROOT_DIR}/scripts/execution-n12-command-publication-verify.py" --mode template
python3 "${ROOT_DIR}/scripts/test_execution_n12_command_publication_verify.py"
python3 "${ROOT_DIR}/scripts/portal-release-authority.py" verify --mode template
python3 "${ROOT_DIR}/scripts/test_portal_release_authority.py"
"${ROOT_DIR}/scripts/test-execution-d4-storage.sh"
"${ROOT_DIR}/scripts/execution-d4-source-proxy-test.sh"
"${ROOT_DIR}/scripts/execution-d4-qualification-preflight-test.sh"
"${ROOT_DIR}/scripts/execution-n06-qualification-test.sh"

while IFS= read -r tracked_path; do
  case "${tracked_path}" in
    */node_modules/*|*/dist/*|*/build/*|*/target/*|*/coverage/*|*/.pytest_cache/*|*/__pycache__/*|*/tsconfig.tsbuildinfo)
      printf 'Generated dependency or build output is tracked by Portal Git: %s\n' "${tracked_path}" >&2
      exit 1
      ;;
  esac
done < <(git -C "${ROOT_DIR}" ls-files)

docker compose --project-directory "${ROOT_DIR}" -f "${ROOT_DIR}/compose.yaml" config --quiet
docker compose --project-directory "${ROOT_DIR}" \
  --env-file "${ROOT_DIR}/deploy/.env.production.example" \
  -f "${ROOT_DIR}/deploy/compose.production.yaml" config --quiet
docker compose --project-directory "${ROOT_DIR}" \
  --env-file "${ROOT_DIR}/deploy/.env.execution-edge.example" \
  -f "${ROOT_DIR}/deploy/compose.execution-edge.yaml" config --quiet
EXECUTION_EDGE_ORIGIN=https://10.70.0.2:8443 \
EXECUTION_EDGE_DELEGATION_AUDIENCE=portal-execution-edge-paper \
CONTROL_API_EXECUTION_EDGE_SECRET_DIRECTORY=/srv/primus/control-api/execution-edge-secrets \
docker compose --project-directory "${ROOT_DIR}" \
  --env-file "${ROOT_DIR}/deploy/.env.production.example" \
  -f "${ROOT_DIR}/deploy/compose.production.yaml" \
  -f "${ROOT_DIR}/deploy/compose.execution-shadow-query.yaml" config --quiet
CONTROL_API_EXECUTION_EDGE_SECRET_DIRECTORY=/srv/primus/control-api/execution-edge-secrets \
docker compose --project-directory "${ROOT_DIR}" \
  --env-file "${ROOT_DIR}/deploy/.env.production.example" \
  -f "${ROOT_DIR}/deploy/compose.production.yaml" \
  -f "${ROOT_DIR}/deploy/compose.execution-current-source.yaml" config --quiet
"${ROOT_DIR}/scripts/execution-d1-test.sh"
"${ROOT_DIR}/scripts/execution-d2-test.sh"
"${ROOT_DIR}/scripts/execution-d3-test.sh"
"${ROOT_DIR}/scripts/execution-image-publication-test.sh"
"${ROOT_DIR}/scripts/execution-n15a-gateway-test.sh"
"${ROOT_DIR}/scripts/execution-n16a-emergency-routing-test.sh"
"${ROOT_DIR}/scripts/execution-n17a-production-dr-test.sh"
"${ROOT_DIR}/scripts/execution-tracking-test.sh"
printf 'Portal monorepo verification passed.\n'
