-- EDS-09b: explicit Portal-owned observation semantics for the local
-- projection revision journal.  This is not a Trading System Event table:
-- it records only revisions of bounded current-page observations accepted by
-- the SGP Control API.

ALTER TABLE execution_profile_projection_journal
  ADD COLUMN observation_authority text NOT NULL DEFAULT 'PORTAL_OBSERVATION'
    CHECK (observation_authority = 'PORTAL_OBSERVATION'),
  ADD COLUMN observation_semantics text NOT NULL DEFAULT 'BOUNDED_CURRENT_PAGE'
    CHECK (observation_semantics = 'BOUNDED_CURRENT_PAGE'),
  ADD COLUMN source_contract_revision text
    CHECK (source_contract_revision IS NULL OR length(btrim(source_contract_revision)) > 0);

-- Existing retained rows were all generated by the local profile projection
-- worker before source-contract revision was persisted per journal row.  Keep
-- that one historical field NULL rather than guessing it from today's
-- snapshot; all new rows are written with their exact accepted revision.
